ligato/vpp-agent

plugins/defaultplugins/error_status.go
tests/go/itest/l2tst/data.go

ODPM-521: errors are no longer logged without iface/bd name in key (vpp-agent)

---

plugins/defaultplugins/l2plugin/fib_config.go
plugins/defaultplugins/l2plugin/vppcalls/l2fib_vppcalls.go

fib.vppChannel is closed in fib config, this called close() on closed channel

ODPM-586: removed redundant fib.vppChannel.Close()

---

plugins/defaultplugins/l2plugin/bd_config.go

ODPM-596: removed interfaces are no longer shown in bd oper state

---

CHANGELOG.md
cmd/vpp-agent-ctl/json/veth1.json
cmd/vpp-agent-ctl/json/veth2.json
examples/localclient_linux/main.go
plugins/defaultplugins/watch_events.go
plugins/linuxplugin/data_resync.go
plugins/linuxplugin/ifaceidx/linux_if_index.go
plugins/linuxplugin/interface_config.go
plugins/linuxplugin/model/interfaces/interfaces.pb.go
plugins/linuxplugin/model/interfaces/interfaces.proto

vEth config allows to define the name of the interface in the host OS different from the one used internally by th agent

Modify vEth config

---

docker/prod_vpp_agent/Dockerfile
docker/prod_vpp_agent/supervisord.conf
docker/prod_vpp_agent/supervisord_kill.py

The pusrpose is to kill supervisord on vpp failure, which
subsequently stops the docker container.
Signed-off-by: Peter Gubka <pgubka@cisco.com>

Set event listener for vpp

---

.travis.yml
scripts/build-vpp.sh

This should fix build issues that occur when the VPP version is updated and Travis tries to use old cached VPP deb packages from previous build, thus failing on step `make test-examples`. 
Now the script will check the VPP cache folder if it contains version that doesn't match and removes it.
I also changed `VPP_COMMIT` variable to retrieve the commit hash directly from vpp submodule. 
Now it is only required to change version at one place during VPP version change, by updating vpp submodule to desired version.
I also added `git -> depth` parameter to **5** in Travis config to save some time when cloning the repository since by default it retrieves **50**. This decreases cloning step by ~10 seconds.

Update build-vpp.sh script for travis

---

docker/dev_vpp_agent/supervisord.conf
docker/prod_vpp_agent/supervisord.conf
tests/perf/vpp.yaml
tests/perf/vswitch-vpp.yaml

The `delay` flag was removed [here](https://github.com/ligato/vpp-agent/commit/25dbfdacd1213243b25e25efdebfd2fe0ef439e9#diff-f4768196b7566ad9dff98fedd6918a77).
This seems to me that **govpp** in the vendor folder was just not updated and committed with required version.  However the last change of required **govpp** version was on [Sep 13](https://github.com/ligato/vpp-agent/commit/01494a5835bf6c6f8fd38c9a3548c7ce046c4893#diff-395f41b2a27b70ce44399c91c82158c2).

Remove deprecated delay flag

---

tests/robot/libraries/vpp_ctl.robot
tests/robot/resources/memif_interface.json

The hard-coded value of mtu parameter in memif_interface.json was changed to the more flexible variable notation and this change is taken into account in the definition of the keyword vpp_ctl: Put Memif Interface

ODPM-668: Robot tests: Added parameter MTU to  vpp_ctl: Put Memif Interface

---

plugins/defaultplugins/ifplugin/bfd_config.go
plugins/defaultplugins/ifplugin/stn_config.go
plugins/defaultplugins/ifplugin/vppcalls/compat_vppcalls.go

- func CheckMsgCompatibilityForBfd passes log but it is not needed. It can be logged into bfd_config
Signed-off-by: Jozef Bacigal <jozef.bacigal@pantheon.tech>

Fix bdf_config func

---

errors/errors.go
plugins/defaultplugins/l3plugin/l3idx/l3_route_index.go
plugins/defaultplugins/l3plugin/route_config.go
plugins/defaultplugins/l3plugin/route_utils.go
plugins/defaultplugins/plugin_impl_vpp.go
plugins/defaultplugins/watch_events.go

It is possible to specify set of routes for not existing
outgoing interface.
Once interface is created than this routes are automatically
configured on VPP.
In case of modification of cached route it is replaced with
new route (if there are same changes in priority or weight fields)
Signed-off-by: Jozef Gloncak <jozef.gloncak@pantheon.tech>

Configuring routes waits for outgoing interface (VPP plugin)

---

plugins/defaultplugins/l2plugin/bd_config.go
plugins/defaultplugins/l2plugin/fib_config.go

To configure FIB entry, it is required to have desired bridge domain and interface already configured on the VPP and also the interface has to be set as a part of the bridge domain. 
In rare cases, the FIB configurator may react on new bridge domain sooner that the bridge domain has all interfaces set and the FIB entry won't be configured. 

register bd after all interfaces are set

---

docker/dev_vpp_agent/Dockerfile
docker/prod_vpp_agent/Dockerfile

This cleans up the Dockerfile for each of the two images.
It makes the following changes:
- installs most packages in the first phase
- removes the apt lists
- uses both g++ and gcc from the gcc7 ppa
- cleans up the formatting of the RUN commands
This reduced the size of the resulting image to 4.78 GB in my testing.

docker/...: optimize & clean up Dockerfiles

---

.gitmodules

This change is required for using vpp-agent as [[constraint]] in Gopkg.toml (dep), since we changed submodule url in pantheon-dev branch.
Without this dep ensure will fail with following error:
```
Solving failure: No versions of github.com/ligato/vpp-agent met constraints:
6203f5baed2c475ef06ae42a8ee23599fc0b6db3: unexpected error while defensively updating submodules: error: no such remote ref 954d43767061e7f78a9080313d645192e3029789
Fetched in submodule path 'vpp', but it did not contain 954d43767061e7f78a9080313d645192e3029789. Direct fetching of that commit failed.
: command failed: [git submodule update --init --recursive]: exit status 1
```

Change url for VPP submodule

---

plugins/defaultplugins/l2plugin/bd_config.go

adding non-bvi interfaces does not crash the agent

---

plugins/defaultplugins/ifplugin/data_resync.go

add af-packet interface to lacal cache during resync

---

Makefile
docker/prod_vpp_agent/Dockerfile

This will build go binaries without debug symbols and DWARF symbol table. Further decreasing production image size.

Strip go binaries in production image

---

cmd/vpp-agent-ctl/data_cmd.go
examples/idx_bd_cache/main.go
plugins/defaultplugins/data_change.go
plugins/defaultplugins/l2plugin/bd_state.go
plugins/defaultplugins/l2plugin/bdidx/bd_index.go
plugins/defaultplugins/l2plugin/bdidx/bd_index_test.go
plugins/defaultplugins/l2plugin/bdidx/fib_index.go
plugins/defaultplugins/l2plugin/data_resync.go
plugins/defaultplugins/l2plugin/fib_config.go
plugins/defaultplugins/plugin_api_vpp.go
plugins/defaultplugins/plugin_impl_vpp.go
plugins/defaultplugins/watch_events.go

* fixed cases where fib entry was not configured in certain if/bd/fib configuration order
* fixed crash if bridge domain was configured after fib
* reactions on new or deleted interface or bridge domain adjusted to latest vpp behavior 
* removed unnecessary FIB meta and casting

refactored fib configurator

---

plugins/defaultplugins/ifplugin/interface_state.go

The PR fixes the scenario:
1, create TAP A
2, delete TAP A
3, create TAP B with a different logical name
4, check notifications/stats
Before the fix the stats for the B interface was printed with the logical name A since swIfIndex was reused and both TAPs have the same swIfIndex.

Fix incorrect logical name in ifstate notifcations

---

plugins/defaultplugins/ifplugin/nat_config.go
plugins/defaultplugins/ifplugin/vppdump/dump_nat_vppcalls.go

- use "|" instead of "-" for separator of DNAT labels (dash is allowed character for K8s service name)
- output features are now separate from the rest of NAT interface features
- Nat44InterfaceDetails with isInside==2 means the interface is both "in" and "out"

NAT configurator bug fixes

---

.travis.yml

Running apt-get update by default has been disabled in Travis recently.

Enable apt update option for Travis

---

plugins/telemetry/README.md
plugins/telemetry/telemetry.go

Change registry path from `/metrics` to `/vpp` for Telemetry statistics from VPP.

Change registry path for Telemetry statistics from VPP

---

plugins/govppmux/vppcalls/vpe_vppcalls.go
plugins/govppmux/vppcalls/vpe_vppcalls_test.go

Fix parsing node counters info when node includes slash

---

Gopkg.lock
Gopkg.toml
Makefile
idxvpp/api.go
plugins/defaultplugins/l2plugin/bd_config.go
plugins/defaultplugins/l2plugin/bdidx/bd_index.go
plugins/defaultplugins/l2plugin/bdidx/bd_index_test.go
plugins/defaultplugins/l2plugin/data_resync.go
plugins/defaultplugins/l2plugin/fib_config.go
plugins/defaultplugins/l2plugin/fib_config_test.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls_test.go
plugins/defaultplugins/watch_events.go
vendor/github.com/ligato/cn-infra/idxmap/api.go
vendor/github.com/ligato/cn-infra/idxmap/mem/inmemory_name_mapping.go

cherry-picked from https://github.com/ligato/vpp-agent/pull/629 and https://github.com/ligato/vpp-agent/pull/630

(contiv) fixed fib resolution where interface is not a part of bridge domain + tests

---

.travis.yml
Makefile
docker/prod/README.md
plugins/vpp/aclplugin/acl_config_test.go

This PR changes both make targets `test`/`test-cover` to run all tests recursively. This will eliminate forgotten tests and count the real coverage.
And this also makes `check-links` target mandatory for Travis check.

Always run all unit tests recursively

---

plugins/vpp/ifplugin/interface_config.go
plugins/vpp/ifplugin/interface_config_test.go

When deleting VPP interface (specifically afpacket) when interface
state DOWN is sent before deletion, it will set connected veth interface
to DOWN too. To prevent this and revert to behaviour before creation of
afpacket, do not send DOWN and just delete the interface.
After this change, the afpacket interface is being correctly deleted and veth interfaces stay in correct state (e.g both are UP instead of one being DOWN and other being LOWERLAYERDOWN). I am not sure why is this happening, maybe another solution is to just not send DOWN only for afpacket and not delete this part of logic completely.
This is what happens currently on `pantheon-dev` when/after DOWN is sent (ignore the error messages, they were only added locally to properly determine starting point of action):
```
DEBU[0044] …
```

Do not send interface DOWN when deleting VPP int

---

plugins/vpp/ifplugin/vppcalls/nat_vppcalls.go
plugins/vpp/ifplugin/vppdump/dump_nat_vppcalls.go

This reverts commit 974aaf62f0ce6ef06c75c0eabcb0e3b7a66a7931.
SelfTwiceNAT is now supported in the currently used VPP.

Revert "Comment out SelfTwiceNat in NAT calls for now"

---

plugins/vpp/ifplugin/data_resync.go

The physical interface details get by "dump" were not updated after VPP
restart. Now VPP interface details are updated in ETCD after
synchronization.

Retrieve the physical VPP interface details via VPP-Agent

---

plugins/vpp/ifplugin/afpacket_config.go
plugins/vpp/ifplugin/interface_config.go
plugins/vpp/ifplugin/vppcalls/afpacket_vppcalls.go
plugins/vpp/ifplugin/vppcalls/afpacket_vppcalls_test.go

Instead of using VPP call to set afpacket hardware address after
creation, do it when creating afpacket interface using afpacket-specific
calls. This prevents afpacket setting its own MAC address to bound veth.

Correctly set afpacket mac

---

plugins/govppmux/vppcalls/vpe_vppcalls.go
plugins/govppmux/vppcalls/vpe_vppcalls_test.go

|string suffix|amount|integer|
|---|---|---|
| `k` | thousands | 1e3 |
| `m` | millions  | 1e6 |
| `g` | billions  | 1e9 |
Format function in VPP code which formats memory size: https://docs.fd.io/vpp/18.07/d2/d8f/std-formats_8c.html#a447abbd57cc963a3794c825410f626b7

Fix parsing billions from VPP stats ('1g' = 1 billion)

---

plugins/vpp/ifplugin/interface_config.go
plugins/vpp/ifplugin/interface_config_test.go

According VPP guy, an interface has to be set down before deleting.
Test-cases are updated to reflect this change.

Set interface down before deleting (except AFPACKET)

---

plugins/vpp/l3plugin/route_config.go

When deleting route prior resolveInterfaceSwIndex() check whether route is not in cache.

Interface being removed before route ends with error

---

plugins/linux/ifplugin/interface_config.go
plugins/linux/ifplugin/interface_config_test.go

Some tests for TAP interfaces started failing recently. Probably after
this change: https://github.com/ligato/vpp-agent/pull/691

Some tests for TAP interfaces started failing

---

plugins/telemetry/telemetry.go

**Default update period**
- previously if not config file was not found, the update period was
never set to default and the reading was done continuously (without sleep)
- now the default will be always set even without any config file
- this also defines minimum allowed update period to be >=5 seconds
**Proper closing**
- this also fixes closing of GoVPP channel, previously it was being closed in   
`Close()` which is not correct, because only producers should close the channels
- now proper stopping of update loop is also handled using quit channel to inform
the loop about the stop

Fix setting telemetry update period to default and closing

---

plugins/govppmux/vppcalls/vpe_vppcalls.go
plugins/govppmux/vppcalls/vpe_vppcalls_test.go

Fix parsing parentheses for 'show node counters' in Telemetry

---

plugins/linux/ifplugin/data_resync.go
plugins/linux/nsplugin/ns_handler.go
plugins/linux/nsplugin/ns_handler_test.go
plugins/linux/nsplugin/system_api.go
tests/linuxmock/netlink_if_handler_mock.go
tests/linuxmock/system_mock.go

created Linux interface gets a link-local IPv6 address by default. This address could cause problems while the interface is switched between namespaces because the IP is not a part of the NB config, and IPv6 may not be enabled in the destination namespace.
Change skips link-local address (it will be not switched between namespaces) if it is the only IPv6 address configured on the interface. 

switch to namespace handles IPv6 addresses

---

examples/localclient_linux/tap/main.go
plugins/linux/ifplugin/interface_config.go
plugins/linux/ifplugin/interface_config_test.go
plugins/vpp/ifplugin/interface_state.go

If Linux tap interface is registered, but not yet available for configuration, no error should be returned. When interface appears in the Linux, an event arrives and cached config will be processed.

fix incorrect linux tap error propagation

---

docker/dev/build.sh
docker/dev/push_image.sh
docker/prod/build.sh
docker/prod/push_image.sh

The changes are inspired by this pull request 
https://github.com/contiv/vpp/commit/535b0614eec1ba8cd0b743d040ead7742c43b14c
There are covered both docker/dev and docker/prod images.
The scripts were rewritten with effort to preserve the previous behaviour when it is possible to pre-set some environment variables then export them and use the newly defined values in scripts instead of defined default values.
Warning: there was removed the sudo command while calling docker command in docker/prod/build.sh what can make problem on not sufficiently set up machines...

Support for building of docker images for ARM64 platform

---

docker/dev/logs.conf

change the logs.conf's "defaultLevel" to "default-level" in order to match the tag `json:"default-level"` in config.go's Config

change the logs.conf's defaultLevel to default-level

---

plugins/vpp/ipsecplugin/data_resync.go
plugins/vpp/ipsecplugin/ipsec_config.go
plugins/vpp/ipsecplugin/vppcalls/dump_vppcalls.go

* security associations are compared, new ones are configured and old ones removed
* all security policy databases are removed and only NB are configured since full spd config cannot be currently dumped
* tunnel interfaces untouched, no API to read them from the VPP

updated IPSec resync

---

plugins/linux/ifplugin/linuxcalls/dump_link_linuxcalls.go

- All linux interfaces are read from default namespace
- The IP address is stored to the output and correctly updated

fix linux interface dump for default namespace

---

plugins/vpp/ifplugin/vppcalls/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/dump_interface_vppcalls_test.go
plugins/vpp/ifplugin/vppcalls/vxlan_vppcalls.go

- IPv6 VRF is created if VxLAN is evaluated as IPv6
- In interface dump, VRF is no longer stored in the field within the proto model but was moved to metadata. The reason is that the IPv4 and IPv6 VRFs are dumped separately and both should be visible in the result.

fix IPv6 VRF for VxLAN

---

examples/kvscheduler/acls/main.go
examples/kvscheduler/nat/main.go
plugins/vppv2/aclplugin/descriptor/acl.go
plugins/vppv2/aclplugin/descriptor/acl_to_interface.go
plugins/vppv2/aclplugin/vppcalls/interfaces_vppcalls.go
plugins/vppv2/ifplugin/descriptor/interface.go
plugins/vppv2/ifplugin/descriptor/interface_crud.go
plugins/vppv2/l3plugin/descriptor/static_route.go
plugins/vppv2/natplugin/descriptor/nat44_dnat.go
plugins/vppv2/natplugin/vppcalls/dump_nat_vppcalls.go
plugins/vppv2/natplugin/vppcalls/dump_nat_vppcalls_test.go
plugins/vppv2/natplugin/vppcalls/nat_vppcalls.go
plugins/vppv2/natplugin/vppcalls/nat_vppcalls_test.go

With these fixes, the resync for Contiv is almost "empty" (when it should be), the only operation is modify on IPNeigh:
* planned operations:
1. MODIFY:
- key: vpp/config/v2/ipneigh
- prev-value: { mode:IPv4 scan_interval:1 max_proc_time:20 max_update:10 scan_int_delay:1 stale_threshold:4  } 
- new-value: { mode:IPv4 scan_interval:1 stale_threshold:4  }
Default values need to be considered in the comparison function, Ondrej would you take care of it?

Fixes for bugs in v2 plugins found with Contiv

---

plugins/vpp/ifplugin/interface_state.go
plugins/vpp/ifplugin/interface_state_test.go

The interfaces stats for TX (out) packets/bytes was missing because of the wrong index for TX counters.

Fix interface counters for TX packets

---

docker/dev/exec_agent.sh
docker/dev/govpp.conf
docker/dev/supervisord_kill.py
docker/prod/govpp.conf
plugins/govppmux/plugin_impl_govppmux.go

- correctly configure GoVPP with defaults even when config file is missing
- configure `DefaultReplyTimeout` in GoVPP instead of   setting it for each request separately
- remove `govpp.conf` from docker images, forcing to use defaults (which were same as in config file)
- change default for health check reply timeout to **250ms**, because it seems that **100ms** is just too short period

Changes in configuration of GoVPP

---

plugins/kvscheduler/graphviz.go
plugins/kvscheduler/internal/graph/graph_read.go
plugins/kvscheduler/internal/test/values.go
plugins/kvscheduler/plugin_scheduler.go
plugins/kvscheduler/resync_test.go
plugins/kvscheduler/txn_exec.go
plugins/kvscheduler/utils_for_test.go

kvscheduler bugfix: revert only if failed value is from the current txn

---

tests/robot/libraries/docker.robot

The version quay.io/coreos/etcd:v3.3.11-arm64 outputs the string 'embed: ready to serve client requests'.

Fix ready-test for newer etcd versions

---

plugins/vpp/ifplugin/descriptor/interface.go
plugins/vpp/ifplugin/descriptor/interface_crud.go

The af-packet mac address cannot be set properly using the 'sw_interface_set_mac_address' since this change causes that the mac address of the adjacent veth interface to change as well. The mac address is set directly in create/delete api for af-packets, so the interface should be re-created at update if the mac was changed.

fixed af-packet mac address update

---

plugins/vpp/ifplugin/descriptor/interface.go
plugins/vpp/ifplugin/descriptor/unnumbered.go

do not set interface back to zero vrf only if the interface is unnumbered

---

plugins/configurator/dump.go
plugins/restapi/handlers.go
plugins/vpp/aclplugin/aclplugin.go
plugins/vpp/aclplugin/vppcalls/acl_vppcalls.go
plugins/vpp/ipsecplugin/ipsecplugin.go
plugins/vpp/ipsecplugin/vppcalls/ipsec_vppcalls.go
plugins/vpp/natplugin/natplugin.go
plugins/vpp/natplugin/vppcalls/nat_vppcalls.go
plugins/vpp/puntplugin/vppcalls/punt_vppcalls.go

This is a quick solution to avoid panic when some VPP plugin we support is not loaded. It requires that our counterpart plugin is not loaded as well. This PR makes sure that both configurator and restapi plugin can handle a missing (non-default) plugin.
A dynamic and more robust solution will most likely require to introduce new value state - `UNSUPPORTED`.

Handle unused (non-default) plugin (without panic).

---

tests/perf/grpc-perf.sh
tests/perf/grpc-perf/etcd.conf
tests/perf/grpc-perf/grpc.conf
tests/perf/grpc-perf/main.go
tests/perf/grpc-perf/run_agent_vpp_and_perf.sh

Hi Ondrej,
take a peek at the script ... perhaps this is what you wanted ... feel free to change it if it is not what you wanted.  The vpp still seems to die early when it receives agent requests.  You can also decide where you want this to live in the folder structure and how it should be built.  I build it when the base script is run ...
-John
PS . Not quite sure how to properly programmatically stop the grpc-perf program ...

add a grpc-perf script for testing ipsec tunnel/routes

---

docs/kvscheduler/kvdescriptor.md

Restore back parts of the kvdescriptor documentation removed by "someone"

---

docs/kvscheduler/kvdescriptor.md

(master) Restore back parts of the kvdescriptor documentation removed by "someone"

---

examples/kvscheduler/mock_plugins/ifplugin/mockcalls/mockcalls.go
examples/kvscheduler/mock_plugins/l2plugin/mockcalls/bd_mockcalls.go
plugins/kvscheduler/bench_test.go
plugins/kvscheduler/plugin_scheduler.go
plugins/kvscheduler/rest.go
plugins/kvscheduler/txn_record.go

KVScheduler benchmarks
------------------------
- starts scheduler together with mocked ifplugin and l2plugin
- configures 1/10/100/1000 number of interfaces with bridge domain
How to run:
- build test binary	`go test -c`
- run all benchmarks:	`./kvscheduler.test -test.run=XXX -test.bench=.`
- with CPU profile:	`./kvscheduler.test -test.run=XXX -test.bench=. -test.cpuprofile=cpu.out`
- analyze profile: `go tool pprof cpu.out`
- with mem profile:	`./kvscheduler.test -test.run=XXX -test.bench=. -memprofile mem.out`
- analyze profile: `go tool pprof -alloc_space mem.out`
- with trace profile:	`./kvscheduler.test -test.run=XXX -test.bench=. -trace trace.out`
- analyze profile: `go tool trace -http=:6060 trace.out`

Add benchmarks for kvscheduler

---

api/models/vpp/l3/keys.go
api/models/vpp/nat/keys.go
pkg/models/models.go
pkg/models/spec.go
plugins/orchestrator/orchestrator.go

- Support no-name keys used for global objects
- Model keys changed for globals (`/settings` suffix is stripped): 
- **proxyarp**
- **ipscanneigh** 
- **nat44**
- Check if registered proto message is empty and recommend fix (proto option)
- Improve error log messages when unmarshalling fails during datasync event processing
- Validate model keys (compares KV key with generated model key from value)

Models & Orchestrator input checks

---

plugins/kvscheduler/internal/graph/node_read.go

Fixes:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x12c204a]
goroutine 66 [running]:
github.com/contiv/vpp/vendor/github.com/ligato/vpp-agent/plugins/kvscheduler/internal/graph.(*targetsDef).getForKey(0x0, 0x0, 0x0, 0xc000703590, 0x48, 0x0, 0x0, 0x0)
/home/rasto/go/src/github.com/contiv/vpp/vendor/github.com/ligato/vpp-agent/plugins/kvscheduler/internal/graph/node_read.go:96 +0x3a
github.com/contiv/vpp/vendor/github.com/ligato/vpp-agent/plugins/kvscheduler/internal/graph.(*node).checkPotentialTarget(0xc0004fb870, 0xc0004fb920)
/home/rasto/go/src/github.com/contiv/vpp/vendor/github.com/ligato/vpp-agent/plugins/kvscheduler/internal/graph/node_write …
```

Fix crash in kvscheduler in case of descriptor with no dependencies

---

plugins/kvscheduler/internal/graph/edge_lookup.go
plugins/kvscheduler/internal/graph/edge_lookup_test.go

Graph benchmark shows that it is better now for higher number of graph nodes/edges.
For example, before:
```
nchmarkScaleWithoutRecInPlace/1-2           	   50000	     27.311 ns/op
BenchmarkScaleWithoutRecInPlace/10-2          	   10000	    236.857 ns/op
BenchmarkScaleWithoutRecInPlace/100-2         	     300	   4.276.406 ns/op
BenchmarkScaleWithoutRecInPlace/1000-2        	      20	  76.376.488 ns/op
BenchmarkScaleWithoutRecInPlace/10000-2       	       1	3.530.690.159 ns/op
```
Now:
```
BenchmarkScaleWithoutRecInPlace/1-2           	   50000	     27.593 ns/op
BenchmarkScaleWithoutRecInPlace/10-2          	   10000	    246.341 ns/op
BenchmarkScaleWithoutRecInPlace/100-2         	     300	   4.484.061 ns/op
BenchmarkScaleWithoutRecInPlace/1000-2        	      20	  56.016.241 ns/op …
```

kvgraph: optimize iterSources to have logarithmic complexity

---

plugins/kvscheduler/plugin_scheduler.go
plugins/kvscheduler/refresh.go
plugins/kvscheduler/txn_record.go

Everyone is now confused that by default transaction logs are not printed anymore. Since these logs are quite essential in that they are the only source of visibility into what is agent doing, I would keep them enabled by default. Furthermore, these logs are separate from logrus-based logging (stdout output vs. per-line logging), therefore I have added a separate config option that would allow to disable transaction  output if needed for performance (e.g. in Kiknos).
Please include this in the upcoming release. Transaction output is also quite referenced in the documentation.
Alternative solution could be to disable transaction output automatically when the bandwidth is high....

kvscheduler: separate transaction summary from logrus-based logging

---

api/models/vpp/l3/keys.go
api/models/vpp/l3/keys_test.go
plugins/vpp/srplugin/descriptor/localsid.go

I know from previous pull requests that Parse key methods are not really wanted, but i couldn't get the info otherwise. If there is a better way, i can change the implementation.

Fixed wrong dependency for SRv6 end functions referencing VRF tables (DT6,DT4,T)

---

plugins/kvscheduler/internal/graph/bench_test.go
plugins/kvscheduler/internal/graph/edge_lookup.go
plugins/kvscheduler/internal/graph/edge_lookup_test.go
plugins/kvscheduler/internal/graph/graph_impl.go
plugins/kvscheduler/internal/graph/graph_read.go

Improved `edgeLookup` from `kvscheduler/internal/graph` to avoid very expensive memmove of data with pointers - from the CPU profile of GRPC perf test:
```
flat  flat%   sum%        cum   cum%
12.83s 33.46% 33.46%     12.83s 33.46%  runtime.memmove
3.20s  8.34% 41.80%      3.20s  8.34%  runtime.futex
2.59s  6.75% 48.55%      2.92s  7.61%  syscall.Syscall
1.41s  3.68% 52.23%      1.41s  3.68%  runtime.usleep
0.74s  1.93% 54.16%      0.74s  1.93%  runtime.epollwait
0.68s  1.77% 55.93%      1.57s  4.09%  runtime.scanobject
0.52s  1.36% 57.29%      2.19s  5.71%  runtime.mallocgc
0.44s  1.15% 58.44%      0.44s  1.15%  runtime.memclrNoHeapPointers
0.41s  1.07% 59.50%      0.41s  1.07%  cmpbody
0.35s  0.91% 60.42%      0.42s  1.10%  runtime.findObject
```
With this improvement, the time spent in …

kvgraph: further performance improvements

---

plugins/vpp/srplugin/descriptor/localsid.go
plugins/vpp/srplugin/vppcalls/api_vppcalls.go
plugins/vpp/srplugin/vppcalls/vpp1901/srv6.go
plugins/vpp/srplugin/vppcalls/vpp1901/srv6_test.go
plugins/vpp/srplugin/vppcalls/vpp1904/srv6.go
plugins/vpp/srplugin/vppcalls/vpp1904/srv6_test.go

Fix for SRv6 localsid delete in nonzero vrf tables

---

plugins/vpp/ifplugin/vppcalls/vpp1901/watch_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1904/watch_vppcalls.go

Even though notifications are processed quickly in separate go
routines, it still may not be enough if multiple of them are
received at roughly the same time, causing potential drops.
Added small buffer for the notification channel.

Make channel for notifications buffered

---

plugins/linux/ifplugin/descriptor/interface.go

This fixes problem with detecting IPv6 address reported in issue #1350.

Fix IPv6 detection

---

plugins/vpp/ifplugin/descriptor/link_state.go
plugins/vpp/ifplugin/publish_state.go

Added temporary logs to help with the issue https://github.com/ligato/vpp-agent/issues/1365
In the reported case it seems that ALL interface state notifications are lost somewhere along the way...

Add some (temporary) debug logs for interface state updates

---

docker/dev/Dockerfile

For building VPP was used gcc-7 which ended by failure on ARM64 platform
gcc-8 and g++-8 are installed and used instead to ensure successfull build
VPP is built with gcc-8 for both platform variants - x86_64 and aarch64 successfully

fix ARM64 docker image build

---

plugins/vpp/ifplugin/ifplugin.go
plugins/vpp/ifplugin/interface_state.go
plugins/vpp/ifplugin/publish_state.go

In the current state, the interface and interface stats plugins are starting goroutines for statistics handling even if no publishers are set. Statistics and counters are read and processed and then dropped since there is nowhere to send them. Changes:
* watcher for status events is started only when at least one status publisher is enabled
* reading counters and updating if-state details is started only when some status publisher or messaging plugin is enabled. Especially `doUpdatesIfStateDetails` may have a major impact since it periodically calls `DumpInterfaces` and was always started.
Since there is no way how to find out whether the messaging plugin is usable (as in this case where the Kafka plugin is hard-coded but mostly disabled), the messaging was temporarily removed from the …

tweaked interface statistics

---

cmd/vpp-agent/app/vpp_agent.go
plugins/configurator/dump.go
plugins/configurator/plugin.go
plugins/govppmux/plugin_impl_govppmux.go
plugins/restapi/handlers.go
plugins/restapi/plugin_restapi.go
plugins/vpp/abfplugin/abfplugin.go
plugins/vpp/abfplugin/vppcalls/abf_vppcalls.go
plugins/vpp/abfplugin/vppcalls/vpp1901/abf_vppcalls_test.go
plugins/vpp/abfplugin/vppcalls/vpp1901/dump_abf_vppcalls.go
plugins/vpp/abfplugin/vppcalls/vpp1901/vppcalls_handlers.go
plugins/vpp/abfplugin/vppcalls/vpp1904/abf_vppcalls_test.go
plugins/vpp/abfplugin/vppcalls/vpp1904/dump_abf_vppcalls.go
plugins/vpp/abfplugin/vppcalls/vpp1904/vppcalls_handlers.go
plugins/vpp/abfplugin/vppcalls/vpp1908/abf_vppcalls_test.go
plugins/vpp/abfplugin/vppcalls/vpp1908/dump_abf_vppcalls.go
plugins/vpp/abfplugin/vppcalls/vpp1908/vppcalls_handlers.go
plugins/vpp/aclplugin/aclplugin.go
plugins/vpp/aclplugin/vppcalls/acl_vppcalls.go
plugins/vpp/aclplugin/vppcalls/vpp1901/acl_vppcalls_test.go
plugins/vpp/aclplugin/vppcalls/vpp1901/dump_vppcalls.go
plugins/vpp/aclplugin/vppcalls/vpp1901/vppcalls_handlers.go
plugins/vpp/aclplugin/vppcalls/vpp1904/acl_vppcalls_test.go
plugins/vpp/aclplugin/vppcalls/vpp1904/dump_vppcalls.go
plugins/vpp/aclplugin/vppcalls/vpp1904/vppcalls_handlers.go
plugins/vpp/aclplugin/vppcalls/vpp1908/acl_vppcalls_test.go
plugins/vpp/aclplugin/vppcalls/vpp1908/dump_vppcalls.go
plugins/vpp/aclplugin/vppcalls/vpp1908/vppcalls_handlers.go

- do not return error for dumps when some handlers are not available
- log all unavailable handlers during initialization of restapi/configurator
- remove unused dump channels from vppcalls

Fix dumps for unavailable handlers

---

plugins/vpp/puntplugin/descriptor/ip_punt_redirect.go
plugins/vpp/puntplugin/descriptor/punt_exception.go
plugins/vpp/puntplugin/descriptor/punt_to_host.go
plugins/vpp/puntplugin/options.go
plugins/vpp/puntplugin/puntplugin.go
plugins/vpp/puntplugin/vppcalls/punt_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1901/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1901/punt_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1904/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1904/punt_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/punt_vppcalls.go

- do not check socket path for punt exceptions to prevent recreation
- add depenency for RX interface to ip redirect punt
- implement IP redirect dump (only for 19.08)
- add workaround for publishing socket to punt exceptions as well
- properly deregister punt exeption on delete
- return pathname from registration when adding punt exception
- add workaround with ! prefix to punt exceptions
- publish socket paths to status with client TTL

Add fixes for punt plugin

---

cmd/vpp-agent-ctl/data/ipsecplugin.go
plugins/vpp/ipsecplugin/vppcalls/vpp1904/ipsec_vppcalls.go
plugins/vpp/ipsecplugin/vppcalls/vpp1904/ipsec_vppcalls_test.go
plugins/vpp/ipsecplugin/vppcalls/vpp1908/ipsec_vppcalls.go
plugins/vpp/ipsecplugin/vppcalls/vpp1908/ipsec_vppcalls_test.go

Fix IPSec SA flags so the tunnel src/dst IP can be configured. Fixed for vpp1904 & vpp1908 (the version 1901 does not use flags).

fix IPSec security associations tunnel mode

---

api/models/vpp/interfaces/keys.go
api/models/vpp/interfaces/keys_test.go
plugins/vpp/ifplugin/descriptor/interface.go
plugins/vpp/ifplugin/descriptor/interface_with_address.go
plugins/vpp/ifplugin/descriptor/unnumbered.go
plugins/vpp/ifplugin/ifplugin.go

Added new property key-value pair which gets derived from interface and created when at least one IP address is assigned. Unnumbered interfaces can then reference this one kv instead of all IP addresses through a key-prefix.
In case of the Kiknos project this decreases the number of edges in the graph from O(n^2) to O(n) where n is the number of IP addresses/tunnels.

Add derived (property) key-value marking interface with at least one IP address

---

Gopkg.lock
plugins/orchestrator/watcher/aggregator.go
vendor/git.fd.io/govpp.git/adapter/socketclient/socketclient.go
vendor/git.fd.io/govpp.git/adapter/stats_api.go
vendor/git.fd.io/govpp.git/adapter/statsclient/stat_segment.go
vendor/git.fd.io/govpp.git/adapter/statsclient/statsclient.go
vendor/git.fd.io/govpp.git/adapter/vpp_api.go
vendor/git.fd.io/govpp.git/adapter/vppapiclient/vppapiclient.go
vendor/git.fd.io/govpp.git/core/channel.go
vendor/git.fd.io/govpp.git/core/connection.go
vendor/git.fd.io/govpp.git/core/log.go
vendor/git.fd.io/govpp.git/core/request_handler.go

Both of these important for kiknos.

Update GoVPP & aggregated watcher

---

plugins/telemetry/config.go
plugins/telemetry/metrics.go
plugins/telemetry/telemetry.conf
plugins/telemetry/telemetry.go

This allows user to skip some of the metrics in telemetry plugin using option in configuration file, e.g `skipped: [nodes]` for skipping node metrics

Add option for skipping metrics in telemetry plugin

---

tests/integration/vpp/020_routes_test.go

routes in default VRF and VRF=2

Added CRUD integration tests for IPv4/IPv6 

---

plugins/kvscheduler/api/txn_record.go
plugins/kvscheduler/datachange_test.go
plugins/kvscheduler/internal/test/model/values.pb.go
plugins/kvscheduler/internal/test/model/values.proto
plugins/kvscheduler/internal/test/southbound.go
plugins/kvscheduler/internal/test/values.go
plugins/kvscheduler/txn_exec.go
plugins/kvscheduler/txn_record.go

This patch fixes issues reported in #1418.
During recreate (Delete+Create) the node would be completely
removed from the graph by Delete and all the associated flags
(metadata) were therefore lost.
When the subsequent Create fails, the scheduler needs to access
the flags, which in this case are undefined, causing the scheduler
to panic by dereferencing nil pointer.
This patch ensures that the node and its flags are preserved
during re-creation.
An in-progress refactor of the scheduling algorithm
will approach value recreation in a much cleaner
way...

kvscheduler: keep node in the graph during recreate

---

plugins/vpp/l3plugin/descriptor/route.go

VRF has to be retrieved before routes.. otherwise we dump nothing for VPP 19.08.

Define VRF as retrieve dependency for routes

---

cmd/agentctl/commands/dump.go

Use new proto message marshalling in dump

Fix agentctl dump command

---

tests/robot/libraries/etcdctl.robot
tests/robot/libraries/vpp_term.py
tests/robot/suites/crud/acl_crud.robot
tests/robot/suites/crud/replyACL/reply_acl1_tcp_term.txt
tests/robot/suites/crud/replyACL/reply_acl1_update_tcp_term.txt
tests/robot/suites/crud/replyACL/reply_acl2_delete_tcp_term.txt
tests/robot/suites/crud/replyACL/reply_acl2_tcp_term.txt
tests/robot/suites/crud/replyACL/reply_acl3_udp_term.txt
tests/robot/suites/crud/replyACL/reply_acl4IPv6_udp_term.txt
tests/robot/suites/crud/replyACL/reply_acl4_udp_term.txt
tests/robot/suites/crud/replyACL/reply_acl5_icmp_term.txt
tests/robot/suites/crud/replyACL/reply_acl6_all_term.txt
tests/robot/suites/crud/replyACL/reply_acl6_icmp_term.txt
tests/robot/suites/crud/replyACL/reply_acl_all_term.txt
tests/robot/suites/crudIPv6/acl_crudIPv6.robot
tests/robot/suites/crudIPv6/replyACL/reply_acl1IPv6_tcp_term.txt
tests/robot/suites/crudIPv6/replyACL/reply_acl1IPv6_update_tcp_term.txt
tests/robot/suites/crudIPv6/replyACL/reply_acl2IPv6_delete_tcp_term.txt
tests/robot/suites/crudIPv6/replyACL/reply_acl2IPv6_tcp_term.txt
tests/robot/suites/crudIPv6/replyACL/reply_acl3IPv6_udp_term.txt
tests/robot/suites/crudIPv6/replyACL/reply_acl4IPv6_udp_term.txt
tests/robot/suites/crudIPv6/replyACL/reply_acl5IPv6_icmp_term.txt
tests/robot/suites/crudIPv6/replyACL/reply_acl6IPv6_all_term.txt
tests/robot/suites/crudIPv6/replyACL/reply_acl6IPv6_icmp_term.txt
tests/robot/suites/crudIPv6/replyACL/reply_aclIPv6_all_term.txt
tests/robot/suites/crudIPv6/replyACL/reply_acl_all_term.txt

- do not check API name and API handler ID in received response
- start moving low-level functionality to Python code

Fix ACL/IPv6ACL CRUD tests

---

Makefile

Running `make` (without specifying any target) or `make help` will now print list of documented make targets.
```
➤ make
List of make targets:
agent                          Build agent
install                        Install commands
cmd                            Build commands
clean-cmd                      Clean commands
examples                       Build examples
clean-examples                 Clean examples
debug-remote                   Debug remotely
test                           Run unit tests
test-cover                     Run unit tests with coverage
perf                           Run quick performance test
perf-all                       Run all performance tests
integration-tests              Run integration tests
generate                       Generate all
generate-proto …
```

Print help with list of targets by default

---

plugins/vpp/aclplugin/vppcalls/vpp1904/acl_vppcalls.go
plugins/vpp/aclplugin/vppcalls/vpp1904/dump_vppcalls.go
plugins/vpp/aclplugin/vppcalls/vpp1908/acl_vppcalls.go
plugins/vpp/aclplugin/vppcalls/vpp1908/dump_vppcalls.go
plugins/vpp/aclplugin/vppcalls/vpp2001/acl_vppcalls.go
plugins/vpp/aclplugin/vppcalls/vpp2001/acl_vppcalls_test.go
plugins/vpp/aclplugin/vppcalls/vpp2001/dump_vppcalls.go
tests/integration/vpp/040_acl_test.go

Fixed in all supported VPP versions:
* ICMP code range 'last' filled with the correct value for IPv6 rule
* Fixed dump of ICMP code range and type range values

Fix ACL ICMP rules

---

plugins/vpp/srplugin/descriptor/steering.go

Signed-off-by: Filip Gschwandtner <filip.gschwandtner@pantheon.tech>

Fixed missed interface dependency for SRv6 L2 steering

---

tests/robot/libraries/setup-teardown.robot

Make path independent of pybot execution directory. Use relative
path from library dir instead.

test: use relative path for copying VPP API executor to device

---

tests/e2e/000_initial_test.go
tests/e2e/010_interfaces_test.go
tests/e2e/011_interface_link_only_test.go
tests/e2e/020_netalloc_test.go
tests/e2e/030_span_test.go
tests/e2e/e2e_test.go
tests/e2e/run_e2e.sh
tests/e2e/utils/http_rest.go

This PR cleans up code for E2E tests.
- using `SetDefaultEventuallyPollingInterval` and `SetDefaultEventuallyTimeout` instead of setting it for each `Eventually(..)` call
- using more consistent and opionately more readable assertions:
- `Expect(err).To(BeNil())` -> `Expect(err).ToNot(HaveOccurred())`
- `Expect(ping(..)).To(BeNil())` -> `Expect(ping(..)).To(Succeed())`
- compiling test agent as `vpp-agent.test` so it's ignored by git and setting version to `TEST_E2E` to make it clear it's special build
- using `set -x` to display the actual commands in `run_e2e.sh` script

test: Cleanup e2e tests

---

tests/robot/suites/crud/afpacket_crud.robot
tests/robot/suites/crudIPv6/afpacket_crudIPv6.robot
tests/robot/tools/vpp_api_executor.py

- implement interfaces dump using VPP python API
- rework afpacket crud tests to use VPP python API instead
- fix and re-enable afpacket CRUD IPv6

test: remove VAT terminal from afpacket CRUD tests

---

tests/robot/libraries/interface/afpacket.robot
tests/robot/libraries/interface/interface_generic.py
tests/robot/libraries/interface/interface_generic.robot

test: add missing libraries for VPP python API handling of interfaces

---

tests/e2e/040_bridge_domain_test.go

Issue: #1489 
Wait a little bit longer for recreation of af-packet interface
**EDIT**: and for TAP interface too

fix: Wait for interfaces after microservice restart in the bridge domain E2E tests

---

plugins/linux/nsplugin/descriptor/microservice.go

Fixes race condition + speeds up microservices detection

fix: Use Docker event listener to detect microservices

---

README.md

docs: fix link to docs about building local image

---

tests/robot/libraries/linux.py
tests/robot/libraries/linux.robot
tests/robot/libraries/vpp_term.py
tests/robot/libraries/vpp_term.robot
tests/robot/suites/crudIPv6/arp_crudIPv6.robot

- implement keywords for reading IPv6 neighbor list
- use IPv6 addresses in test

test: fix IPv6 ARP CRUD tests using ipv4 addresses

---

tests/robot/libraries/docker.robot

Jenkins tests occasionally fail due to exceeding the 15sec timeout.

test: increase agent setup timeout in robot tests

---

plugins/configurator/dump.go
plugins/configurator/options.go
plugins/configurator/plugin.go
plugins/linux/ifplugin/descriptor/interface.go
plugins/linux/ifplugin/descriptor/interface_address.go
plugins/linux/ifplugin/descriptor/interface_tap.go
plugins/linux/ifplugin/descriptor/interface_veth.go
plugins/linux/ifplugin/ifplugin.go
plugins/linux/ifplugin/linuxcalls/dump_interface_linuxcalls.go
plugins/linux/ifplugin/linuxcalls/netlink_api.go
plugins/linux/l3plugin/descriptor/arp.go
plugins/linux/l3plugin/descriptor/route.go
plugins/linux/l3plugin/l3plugin.go
plugins/linux/l3plugin/linuxcalls/arp_linuxcalls.go
plugins/linux/l3plugin/linuxcalls/dump_arp_linuxcalls.go
plugins/linux/l3plugin/linuxcalls/dump_l3_linuxcalls.go
plugins/linux/l3plugin/linuxcalls/dump_route_linuxcalls.go
plugins/linux/l3plugin/linuxcalls/netlink_api.go
plugins/linux/l3plugin/linuxcalls/route_linuxcalls.go
plugins/linux/nsplugin/ns_plugin.go
plugins/restapi/handlers.go
plugins/restapi/options.go
plugins/restapi/plugin_restapi.go
plugins/restapi/resturl/urls.go
plugins/vpp/ifplugin/descriptor/interface_crud.go
plugins/vpp/ifplugin/ifplugin.go
plugins/vpp/ifplugin/options.go
tests/e2e/010_interfaces_test.go
tests/e2e/011_interface_link_only_test.go

* Linux interface, ARP and route descriptor have dedicated `dump` method in the linuxcalls. The simple `get` (calling netlink API) was kept untouched. 
* Linux interface API offers methods to dump Linux interfaces from namespaces provided in the form of a parameter `nsList`, or call simple `DumpInterfaces()` to obtain all known interfaces from the default namespace and also from other namespaces known to the agent (via local cache).
* Method `DumpInterfaceStats()` retrieves interface statistics (in the similar manner as for VPP). Since there is currently no protobuf model for these data, they are not available for the GRPC.
* GRPC and HTTP handlers are using new methods to retrieve data (which means that the respective HTTP call does not read all the Linux interfaces from the default …

feat: GRPC retrieve for linux plugins

---

plugins/vpp/ifplugin/vppcalls/vpp1904/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1904/gtpu_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1904/gtpu_vppcalls_test.go
plugins/vpp/ifplugin/vppcalls/vpp1908/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1908/gtpu_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1908/gtpu_vppcalls_test.go
plugins/vpp/ifplugin/vppcalls/vpp2001/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001/gtpu_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001/gtpu_vppcalls_test.go
plugins/vpp/ifplugin/vppcalls/vpp2001_324/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001_324/gtpu_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001_324/gtpu_vppcalls_test.go

- Fixed the type guessing for GTPU tunnels.
- Added an extra nil check to the GTPU tunnel add and del functions
to avoid problems with older VPP releases that still have a broken get
api.

fix: added GTPU to the interface type guessing function

---

plugins/vpp/ifplugin/descriptor/interface.go
plugins/vpp/ifplugin/descriptor/interface_crud.go
plugins/vpp/ifplugin/vppcalls/vpp1904/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1908/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001_324/dump_interface_vppcalls.go
tests/integration/vpp/090_vxlan_gpe_test.go
tests/integration/vpp/100_gtpu_test.go

- During interface discovery, when any unnumbered interface referenced another interface without a tag, the VRF and IP address values could not be resolved and the delete operation failed.
This resolution was performed in the interface implementation but the name was only set later in the descriptor. This change moves the setting of the interface name earlier so that it is available already in the dump interfaces function.
- The above change uncovered a bug: 0 is a valid interface index (local0), but it was used as the multicast interface index for vxlan and gtpu tunnels when no multicast should be set. The integration tests were working only because the dump interfaces function returned an empty name for local0.
In my setup, gtpu_tunnel0 is an unnumbered interface using loop0. The …

fix: Unnumbered interface name

---

plugins/vpp/srplugin/vppcalls/api_vppcalls.go
plugins/vpp/srplugin/vppcalls/vpp1904/srv6_dump.go
plugins/vpp/srplugin/vppcalls/vpp1908/srv6_dump.go
plugins/vpp/srplugin/vppcalls/vpp2001/srv6_dump.go
plugins/vpp/srplugin/vppcalls/vpp2001_324/srv6_dump.go
tests/integration/vpp/110_srv6_test.go

Rewritten some CRUD robot test for SRv6 localsids (except of SR-proxy localsid due to more complicated approach for dumping data for SR-proxy localsids). This includes some localsid dump support on vppcalls level (tests needed verification of data written to VPP)

test: added basic integration tests for SRv6 Localsids

---

plugins/linux/iptablesplugin/descriptor/rulechain.go
plugins/linux/iptablesplugin/linuxcalls/iptables_api.go

Noticed I've forgot to `git add` this changes yesterday. Comments fixing is the most important part in here :)
- Switch back to the default namespace asap. 
_problem PR fixes:_ 
if `d.ipTablesHandler.ListRules()` returns error, call `continue` and skip switching to default network ns.
- Return early if no rule chain is present.
_problem PR fixes:_ 
check if `if goRoutinesCnt == 0 ` and it could happen only if `correlate` is empty. Set it to 1 and call `retrieveRuleChains` anyway.

refactor: Retrieve method for descriptor in iptables plugin

---

plugins/linux/ifplugin/descriptor/interface_address.go
tests/e2e/020_netalloc_test.go

cherry-pick: f0f912e660e474226b1ac5aa418d03b2d93cad16 (#1586)

fix: duplicate linux addr

---

plugins/telemetry/options.go
plugins/telemetry/stats_poller.go
plugins/telemetry/telemetry.go

fix: Fix interface name in stats poller service (dev)

---

scripts/make/buf.make

ci: Allow breaking change check to fail

---

docker/prod/Dockerfile

Looks like it was removed by accident. Current behaviour:
```sh
➜ docker run -it --rm --name agent1 --privileged ligato/vpp-agent
INFO[0000] Starting agent version: v3.0.0-beta.2-10-gf4e780adb  BuildDate="2020-01-28T12:31+00:00" CommitHash=f4e780adb77b7959e830ba066b163e9d8706cf37 loc="agent/agent.go(134)" logger=agent
panic: failed to retrieve supervisor config file: failed to load supervisor config file: not found
goroutine 1 [running]:
main.main()
/src/ligato/vpp-agent/cmd/vpp-agent-init/main.go:28 +0xda
➜
```
and if path to supervisor.conf passed as env variable:
```sh
➜  docker run -it --rm --name agent1 --privileged -e SUPERVISOR_CONFIG=/opt/vpp-agent/dev/supervisor.conf ligato/vpp-agent
INFO[0000] Starting agent version: v3.0.0-beta.2-10-gf4e780adb …
```

Bring back env var with path to supervisor config

---

plugins/vpp/ifplugin/vppcalls/vpp2001/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001/tap_vppcalls.go

This adds missing default values to tapv2 binapi requests that was causing e2e tets to fail.

fix: Fix VPP TAP dump/create

---

.travis.yml

Checks are now done by GitHub actions in workflow `CI`.

ci: Remove check stage from travis

---

plugins/govppmux/config.go
plugins/govppmux/plugin_impl_govppmux.go
plugins/vpp/ifplugin/descriptor/dhcp.go
plugins/vpp/ifplugin/descriptor/interface.go
plugins/vpp/ifplugin/descriptor/interface_crud.go
plugins/vpp/ifplugin/descriptor/interface_vrf.go
plugins/vpp/ifplugin/ifplugin.go
plugins/vpp/ifplugin/interface_state.go
plugins/vpp/ifplugin/vppcalls/interface_handler_api.go
plugins/vpp/ifplugin/vppcalls/vpp1904/watch_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1904/watch_vppcalls_test.go
plugins/vpp/ifplugin/vppcalls/vpp1908/watch_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1908/watch_vppcalls_test.go
plugins/vpp/ifplugin/vppcalls/vpp2001/watch_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001/watch_vppcalls_test.go
plugins/vpp/vpp.go
plugins/vpp/vppmock/vppmock.go
tests/integration/vpp/integration_test.go

This PR contains these changes:
- fixes watching VPP events after reconnection of VPP
- properly handles unsubscribing from VPP notifications
- sets `ReconnectResync` to true by default

fix: Fix watching VPP events

---

plugins/linux/iptablesplugin/descriptor/rulechain.go
plugins/linux/iptablesplugin/iptablesplugin.go
plugins/linux/iptablesplugin/linux-iptablesplugin.conf
plugins/linux/iptablesplugin/linuxcalls/iptables_api.go
plugins/linux/iptablesplugin/linuxcalls/iptables_linuxcalls.go

The performance enhancement is based on usage of `iptables-save`/`iptables-restore`. It can speed up insertion of rules into chain significantly, but it is different approach then use of more generic `iptables` tool.
Due to changing `iptables-save`-exported data that are in not well documented format (not an API in classic sense), i made this performance enhancement optional and by default turned off.
The usage of this method is regulated by rule count that we want to insert into chain. So inserting few rules that can be quick also with generic `iptables` tool can benefit from stability of `iptables` tool API. Inserting many rules will switch to performance method and can be done much more quickly, but with possibility of future incompatibility break. The data export format can change …

perf: Performance enhancement for adding many rules to Linux IPtables chain

---

plugins/vpp/ifplugin/vppcalls/vpp1908/ipip_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001/ipip_vppcalls.go
tests/integration/vpp/120_ipip_test.go

fix: Fix creation of multiple ipip tunnels

---

plugins/kvscheduler/descriptor_handler.go
plugins/vpp/ipsecplugin/descriptor/tun_protect.go
tests/e2e/070_ipsec_test.go

fix: Fix IPSec tun protect + add IPSec e2e test

---

plugins/vpp/l2plugin/vppcalls/vpp2005/bridge_domain_vppcalls.go
plugins/vpp/l2plugin/vppcalls/vpp2005/dump_vppcalls.go

InterfaceIndex has to be set to max uint32 to properly dump all interfaces.

fix: Fix bridge domain dump for VPP 20.05

---

plugins/vpp/ipsecplugin/vppcalls/vpp2005/ipsec_vppcalls.go
plugins/vpp/ipsecplugin/vppcalls/vpp2005/ipsec_vppcalls_test.go

fix: Fix IPSec SA add/del in VPP 20.05

---

plugins/vpp/ifplugin/vppcalls/vpp1904/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1904/helpers.go

Check if HostIfName contains non-printable characters

---

tests/e2e/100_agentctl_test.go

fix: Update expected output of agentctl status command

---

plugins/vpp/ifplugin/vppcalls/vpp2005/dump_interface_vppcalls.go

This PR should fix resync issue for VPP TAPs with tunnel mode.
It will work correctly when this VPP change gets merged: https://gerrit.fd.io/r/c/vpp/+/27769

fix(vpp/ifplugin): Recognize interface name prefix "tun" as TAP

---

plugins/restapi/handlers.go

That handler:
```go
func (p *Plugin) commandHandler(formatter *render.Render) http.HandlerFunc {
```
was moved to govppmux in this PR: https://github.com/ligato/vpp-agent/pull/1593.
And from that point (after the PR was merged), new home for the handler is here:
https://github.com/ligato/vpp-agent/blob/6ba0dbb39e7b96f05fd11caac2df7667b88864a2/plugins/govppmux/rest.go#L58

refactor: Delete unused REST handler for VPP commands

---

README.md

Badge created using https://pkg.go.dev/badge/ .
The badge points to docs of `go.ligato.io/vpp-agent/v3` module, instead of `github.com/ligato/vpp-agent`.

docs: Update Go doc badge

---

plugins/vpp/srplugin/vppcalls/vpp1904/srv6.go
plugins/vpp/srplugin/vppcalls/vpp1908/srv6.go
plugins/vpp/srplugin/vppcalls/vpp2001/srv6.go
plugins/vpp/srplugin/vppcalls/vpp2005/srv6.go

```sh
plugins/vpp/srplugin/vppcalls/vpp1904/srv6.go:175: conversion from uint32 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL	go.ligato.io/vpp-agent/v3/plugins/vpp/srplugin/vppcalls/vpp1904 [build failed]
plugins/vpp/srplugin/vppcalls/vpp1908/srv6.go:174: conversion from uint32 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL	go.ligato.io/vpp-agent/v3/plugins/vpp/srplugin/vppcalls/vpp1908 [build failed]
plugins/vpp/srplugin/vppcalls/vpp2001/srv6.go:175: conversion from uint32 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL	go.ligato.io/vpp-agent/v3/plugins/vpp/srplugin/vppcalls/vpp2001 [build failed] …
```

test: Fix failing unit test for go1.15

---

tests/integration/vpp/110_srv6_test.go

A fix in VPP was merged into stable branch for 19.08 only...
-> https://gerrit.fd.io/r/gitweb?p=vpp.git;a=commit;h=4362672562f5b379361f147cbb7a9b72c3332c30
this causes VPP 19.08 fail even though it actually is only versions it works okay in..

test(integration): Skip failing test for SRv6 localsids

---

plugins/govppmux/plugin_impl_govppmux.go
plugins/linux/nsplugin/ns_plugin.go
plugins/vpp/ifplugin/vppcalls/vpp1904/watch_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1908/watch_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001/watch_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2005/watch_vppcalls.go

fix: Fix log level and formatting of some logs

---

plugins/vpp/ifplugin/descriptor/interface_crud.go
plugins/vpp/ifplugin/ifaceidx/ifaceidx.go
plugins/vpp/ifplugin/vppcalls/interface_handler_api.go
plugins/vpp/ifplugin/vppcalls/vpp1908/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2005/dump_interface_vppcalls.go

feat: Store interface internal name & dev type as metadata

---

plugins/govppmux/plugin_impl_govppmux.go
plugins/telemetry/stats_poller.go
plugins/telemetry/telemetry.go
plugins/vpp/ifplugin/interface_state.go

This fixes situations where agent cannot connect to stats or when there is with compatibility, e.g. when stats segment version changes. This fixes VPP 20.09 support until GoVPP is compatible with version 2 of stat segment (already in progress by @VladoLavor)

Permit agent to run even when VPP stats are unavailable

---

plugins/vpp/ifplugin/descriptor/interface_address.go

A check in Delete operation in interface_address descriptor was preventing deletion of IPv4 link-local addresses (from the 169.254.0.0/16 range). That was causing multiple IPv4 addresses applied on a single interface after subsequent update operations.
This check only makes sense for IPv6 link-local addresses, which are auto-assigned by VPP on IPv6-enabled interfaces.
Signed-off-by: Rastislav Szabo raszabo@cisco.com

fix: Fix IPv4 link-local IP address handling

---

cmd/agentctl/commands/import.go

Timeout was always zero and not the default 30s or whatever has been configured.

fix: Fix grpc context timeout for agentctl import command

---

plugins/telemetry/prometheus.go

fix: maps caching prometheus gauges weren't really used

---

.travis.yml
plugins/vpp/binapi/vpp2009/wireguard/wireguard.ba.go

This PR disables `allowed_failures` in travis for VPP 20.09. It also contains minor formatting fix for genrated binapi of wireguard in vpp2009 to avoid failing integration test.

Disable allowed failures for VPP 20.09

---

plugins/configurator/configurator.go
plugins/linux/ifplugin/descriptor/watcher.go
plugins/linux/nsplugin/ns_plugin.go

This PR is a fix for #1739
Agent log showing all received notifications for same config as in #1734:
```
+======================================================================================================================+
| #0 - NBTransaction                                                                                        FullResync |
+======================================================================================================================+
* transaction arguments:
- seqNum: 0
- type: NB Transaction, Full Resync
- values:
o----------------------------------------------------------------------------------------------------------------------o
* executed operations:
<NONE>
x------------------------------------------------------------------------------------------------- …
```

Remove forced delay for linux interface notifications

---

tests/e2e/080_vrf_test.go

test(e2e): Disable VRF tests for Travis CI for now.

---

examples/vpp_stats/main.go
plugins/govppmux/vppcalls/vpp1908/vpe_vppcalls.go
plugins/govppmux/vppcalls/vpp2001/vpe_vppcalls.go
plugins/govppmux/vppcalls/vpp2005/vpe_vppcalls.go
plugins/govppmux/vppcalls/vpp2009/vpe_vppcalls.go
plugins/govppmux/vppcalls/vpp_handler_api.go
plugins/telemetry/prometheus.go
plugins/telemetry/vppcalls/telemetry_handler_api.go
plugins/telemetry/vppcalls/telemetry_stats.go
plugins/telemetry/vppcalls/vpp1908/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vpp1908/telemetry_vppcalls_test.go
plugins/telemetry/vppcalls/vpp2001/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vpp2001/telemetry_vppcalls_test.go
plugins/telemetry/vppcalls/vpp2005/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vpp2005/telemetry_vppcalls_test.go
plugins/telemetry/vppcalls/vpp2009/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vpp2009/telemetry_vppcalls_test.go

* Added 'GetThreads' for all supported VPP versions in
the telemetry vppcalls. Data are read using the
binary API (via govppmux)
* VPP stats API telemetry handler also has CLI/binapi
part in order to read data not yet available in stats
* Added simple stats example reading VPP stats via the
telemetry plugin
* Fixed 'GetMemory' regex + added 'verbose' output to 
match VPPTop requirements
TODO:
* ~Fix 'GetMemory' and add it to the example~

feat: add reading VPP threads to the telemetry plugin

---

cmd/agentctl/client/api.go
cmd/agentctl/client/client.go
cmd/agentctl/client/vpp.go
cmd/agentctl/commands/commands.go
cmd/agentctl/commands/report.go

Adding new "report" command to agentctl that retrieves all kind of informations from VPP-Agent/VPP and pack it into one zip file. The reason for this is to speed up the problem resolution that users can have with VPP-Agent (report zip file will provide info that can identify many problems and additional time don't have to be wasted by requesting/sending additional information).

feat: Added reporting capabilities to agentctl

---

cmd/agentctl/commands/config.go
go.mod
go.sum

The argument was previously removed due to implementation replace from configurator to generic client (https://github.com/ligato/vpp-agent/pull/1754)
Also adding go dependecy fix for current master.

Restored --replace argument for agenctl config update

---

pkg/models/api.go
pkg/models/item.go
pkg/models/registry.go

This small PR allows to register models learned remotely (i.e. over gRCP using the meta service) into the LocalRegistry.
Why is this useful?
This change can be used as a building block for integration of multiple (distributed) CNFs (pairs of agent + some data-plane component) into one appliance with a single API endpoint. A central agent can dynamically discover all CNFs, learn their models over gRPC and generate kv descriptors for them that would mostly just forward CRUD operations via remoteclient.
So basically the change allows the following configuration sequence:
```
agentctl/etcd/... -> [proxy agent(s) ->]  target agent
```
To proxy a given model one would write something like:
```
client, err = remoteclient.NewClientGRPC(grpcConn, remoteclient.UseRemoteRegistry("config"))
models, …
```

feat: proxied models (remotely learned models used in DefaultRegistry)

---

plugins/linux/ifplugin/descriptor/interface_vrf.go

fix: add missing return statements for EXISTING Linux interface VRF assignment

---

pkg/models/remote_model.go
plugins/vpp/l3plugin/descriptor/dhcp_proxy.go
proto/ligato/vpp/l3/models.go
tests/e2e/13_dhcp_proxy_test.go

Multiple bug fixes for (probably not much used) DHCP proxy:
1. The key should not only include the IP version but also the VRF ID. In VPP it is possible to configure one DHCPv4/6 proxy for every VRF (as a source of DHCP requests, i.e. `RxVrf`).
2. Labels of DHCP proxy dependencies were not necessarily unique.
3. There was a bug in `RemotelyKnownModel` which would affect DHCP proxy model: `replaceFieldNamesInNameTemplate` would modify any part of the name template, not only field references that start with "." (replace from `IpAddress` to `ipAddress` would also change `sourceIpAddress` to `sourceipAddress`)
All e2e tests pass (including one more added for DHCP Proxy).

fix: dhcp proxy key should include the Rx-VRF ID

---

client/local_client.go
clientv2/vpp/dbadapter/data_change_db.go
clientv2/vpp/dbadapter/data_resync_db.go
cmd/vpp-agent/app/vpp_agent.go
pkg/models/model.go
pkg/models/models.go
pkg/models/options.go
pkg/models/registry.go
pkg/models/remote_model.go
plugins/configurator/configurator.go
plugins/orchestrator/contextdecorator/context.go
plugins/orchestrator/dispatcher.go
plugins/orchestrator/localregistry/initfileregistry.go
plugins/orchestrator/localregistry/nbinitfileregistry.go
plugins/orchestrator/meta_service.go
plugins/orchestrator/orchestrator.go
plugins/orchestrator/store.go
plugins/orchestrator/watcher/aggregator.go
tests/e2e/000_initial_test.go
tests/e2e/100_agentctl_test.go
tests/e2e/e2e.go
tests/e2e/etcd.go
tests/e2e/options.go
tests/e2e/run_e2e.sh
tests/e2e/vppagent.go

Added possibility to define NB configuration as file and to picked up and applied by VPP-Agent at start.
Additional features:
- file defined as yaml
- ability to set up also 3rd party models (using the same components as are used for `agentctl config update --replace`, see [this issue](https://github.com/ligato/vpp-agent/issues/1767) for understanding more about 3rd party model definition/problems)
- by default active, no additional configuration needed to use (create `nb-initial-config.yaml` in vpp-agent working directory, i.e. if you installed vpp-agent binary in one of paths from env.variable then `nb-initial-config.yaml` must be in that directory where you are when you execute vpp-agent binary - if you are still not sure about the location, don't worry, VPP-agent will tell you in …

feat: Added possibility to setup NB configuration from file at VPP-Agent start

---

plugins/linux/ifplugin/descriptor/interface.go
tests/e2e/012_linux_interfaces_test.go

Extended one of the e2e tests such that it fails due to this bug. 
With the fix all e2e tests pass successfully.

fix: Fix metadata Update for Linux interfaces

---

plugins/orchestrator/watcher/aggregator.go

When using init file for importing configuration data by VPP-Agent start and then you try to delete them by resync with empty configuration (using agentctl) then failure happens (this is not the case for using agentctl config delete). The root cause of this is different data source of init file data and data that can agentctl work with. The data source behaves for resyncs similar to linux namespaces, you can't clean data from different data source/namespace (agentctl works with 'grpc' data source data and init file data are 'datasync'-data-source data).
The fix provided by this PR enables the user to configure the init file data to have different data source (i.e.'grpc' to be compatible with agentctl resync). However, due to aggregating of data from multiple data sources (aggregator …

fix: fixed delete by resync failure of init file data by using agentctl

---

plugins/govppmux/plugin_impl_govppmux.go

This state was added recently to GoVPP but govppmux plugin did not yet recognize it, thus not reporting as unhealthy which in cases can lead to _broken instance_ if the communication with VPP is not restored.

fix: Report VPP not responding state as unhealthy status

---

client/local_client.go
pkg/models/model.go
pkg/models/models.go
pkg/models/options.go
pkg/models/registry.go
pkg/models/remote_model.go
pkg/util/proto.go
plugins/kvscheduler/validation.go
plugins/orchestrator/localregistry/initfileregistry.go
plugins/restapi/handlers.go
plugins/restapi/options.go
plugins/restapi/plugin_restapi.go
plugins/restapi/resturl/urls.go

Added ability to change NB VPP-Agent configuration by REST API.
- Use GET REST action on `<VPP-Agent IP address>:9191/configuration` to retrieve NB VPP-Agent configuration in YAML format.
- Use PUT REST action on `<VPP-Agent IP address>:9191/configuration` with configuration to update in YAML format in http body to update NB VPP-Agent configuration.
- Also resync is possible by using PUT REST action on `<VPP-Agent IP address>:9191/configuration?replace=true` (`<VPP-Agent IP address>:9191/configuration?replace` will do the same).
The structure of YAML in all cases is the same as for `agentctl config ...` commands. Basically, it can be viewed as REST API equivalent to `agentctl config get`, `agentctl config update`, `agentctl config update --replace`. However, the REST API output is always …

feat: added REST API for getting and setting NB VPP-Agent configuration

---

examples/localclient_linux/vrf/main.go
plugins/linux/ifplugin/descriptor/interface.go

Default mtu for vrf is set to 65536. The value was changed in recent linux kernels
to 65535 (ETH_MAX_MTU) + size of IPv6 header (40 octets) resulting in mtu 65575.
The latest kernel sets this value by default.
I don't know the exact kernel version where the change has taken place, but it was
somewhere between  5.11.0-27-generic to 5.11.0-37-generic (tested empirically).
More info here: https://www.spinics.net/lists/stable/msg476226.html
Without the patch, resync modifies MTU (from linux-default to agent-default) without 
change in the data. The patch causes that both values are considered as default in case
the new MTU is undefined.
Added simple example to localclient-linux testing vrf device.

fix: default linux vrf device mtu for latest linux kernels

---

proto/ligato/vpp/interfaces/interface.proto

Fixes https://github.com/PANTHEONtech/StoneWork/issues/15.
Replaces `'` with backtick quotes so that Markdown doesn't interpret the text inside.
Also fixes a broken link unrelated to the issue above.

docs: Fix documentation comment formatting

---

plugins/telemetry/vppcalls/vpp2101/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vpp2106/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vpp2202/telemetry_vppcalls.go

It seems to me that these print statements shouldn't be there.
VPP 2005 and 2009 files don't have them either.

fix: remove unnecessary print statement

---

docker/dev/Dockerfile

Some dependency of delve debugger got recently upgraded and as a result delve requires Go 1.18.
That broke the dev-image build as we still use Go 1.17.6. This PR pins the delve version to 1.9.0 so that the dev-image build succeeds.

fix: Pin delve version to v1.9.0

---

cmd/agentctl/commands/config.go
plugins/kvscheduler/internal/utils/record.go

When calling agentctl config history, just query the remote models with
grpc client and add them to the global default model registry.
Then when we unmarshal the messages we primarily use the default registry and
the proto global registry is used as a fallback.

fix: agentctl config history not working with remote models

---

tests/e2e/100_agentctl_test.go

This PR fixes (by creating the required config file inside shared directory for e2e tests) and enables some `agentctl import` tests.
It also enables an `agentctl values` test that now passes without issues.

fix: Restore some agentctl e2e test cases

---

go.mod
go.sum

Cobra 1.5.0 comes with some useful features like mutually exclusive flags and flags that are required together.

build: Update Cobra to v1.5.0

---

tests/e2e/etcd.go

The etcd:latest tag got deprecated and the latest image now does not exist in the [container registry](https://console.cloud.google.com/gcr/images/etcd-development/GLOBAL/etcd). As a result some e2e tests started failing. This PR fixes this problem by using existing v3.5.5 tag.

fix(e2e): Pin etcd image version to v3.5.5

---

client/local_client.go
plugins/orchestrator/contextdecorator/context.go
plugins/orchestrator/orchestrator.go

Due to limitations of cn-infra library config labels were never working properly for local client. For now, user should use remote client for this functionality.

Remove config item labels support from local client

---

plugins/telemetry/config.go
plugins/telemetry/options.go
plugins/telemetry/telemetry.go
plugins/vpp/ifplugin/interface_state.go
plugins/vpp/ifplugin/metrics.go

This PR adds the option to modify the default config of the telemetry plugin.
Additionally 2 new metrics were added - operational and admin state of available interfaces.

feat: Allow modification of default telemetry config, add metrics

---

cmd/agentctl/commands/config.go
pkg/models/registry.go
plugins/kvscheduler/api/api_test.go
plugins/kvscheduler/api/kv_scheduler_api.go
plugins/kvscheduler/api/txn_record.go
plugins/kvscheduler/internal/registry/registry_impl.go
plugins/kvscheduler/plugin_scheduler.go
plugins/kvscheduler/txn_exec.go
plugins/kvscheduler/txn_process.go
plugins/kvscheduler/txn_queue.go
plugins/kvscheduler/txn_record.go
plugins/orchestrator/orchestrator.go
plugins/orchestrator/watcher/aggregator.go

This PR introduces new transaction type inside scheduler implementation. This transaction type is used when for a given configuration key, scheduler does not yet have the corresponding descriptor inside its registry. Instead of the operation being in the unimplemented state indefinitely, it gets retried when the descriptor eventually gets registered.
P.S. I am not sure where (in which package/file) to put the `Broadcast[T]` struct as its usage does not need to be tied to the scheduler itself.
Signed-off-by: Peter Motičák [peter.moticak@pantheon.tech](mailto:peter.moticak@pantheon.tech)

feat: Add txn type for unimplemented configuration

---

client/dynamic_config.go

This PR removes some redundant/misleading logging that happened during construction of dynamic configuration.
Signed-off-by: Peter Motičák [peter.moticak@pantheon.tech](mailto:peter.moticak@pantheon.tech)

fix: Remove redundant logging

---

plugins/vpp/puntplugin/puntplugin.go

In this commit, I have made a modification to the code by changing the type of the variable assignment from *vpp_punt.Exception to *vpp_punt.ToHost. 
The change was made to ensure proper compatibility and consistency within the affected section.

fix: changing type of variable assignment
