ligato/vpp-agent

defaultplugins/error_status.go
defaultplugins/ifplugin/model/interfaces/interfaces.pb.go
defaultplugins/ifplugin/model/interfaces/interfaces.proto
defaultplugins/l2plugin/model/l2/l2.pb.go
defaultplugins/l2plugin/model/l2/l2.proto

all errors belonging to the same interface are stored under one key

---

Makefile
cmd/agentctl/testing/data.go
cmd/agentctl/utils/common_utils.go
cmd/agentctl/utils/common_utils_test.go
cmd/agentctl/utils/db_utils.go
cmd/agentctl/utils/db_utils_test.go
cmd/agentctl/utils/interface_utils.go
cmd/agentctl/utils/interface_utils_test.go
cmd/agentctl/utils/prefix_stack.go
cmd/agentctl/utils/prefix_stack_test.go
cmd/agentctl/utils/print_json.go
cmd/agentctl/utils/print_json_test.go
cmd/agentctl/utils/print_table.go
cmd/agentctl/utils/print_text.go
cmd/agentctl/utils/tree_writer.go
cmd/agentctl/utils/tree_writer_test.go
cmd/vpp-agent-ctl/main.go
defaultplugins/error_status.go
defaultplugins/ifplugin/model/interfaces/keys_agent_interfaces.go
defaultplugins/l2plugin/model/l2/keys_agent_l2.go

added unit tests to agentctl + enable coverage tracking

---

cmd/agentctl/utils/print_text.go

fixed agentctl interface template

---

cmd/vpp-agent-ctl/topology_xcon.sh
cmd/vpp-agent-ctl/topology_xcon_modify.sh

ODPM-498: added topology scripts with l2 xconnect

---

.gitignore
examples/idx_veth_cache/main.go
examples/localclient_vpp/main.go
flavors/linuxlocal/local_flavor.go
flavors/local/local_flavor.go

remove etcd from local flavor

---

tests/robot/libraries/vat_term.robot
tests/robot/suites/crud/loopback_crud.robot

added loopback crud tests

---

README.md

docker exec -it vpp agentctl -e 172.17.0.1:2379 show

---

flavors/local/local_flavor.go
flavors/vpp/vpp_flavor.go
vendor/github.com/ligato/cn-infra/datasync/kvdbsync/plugin_impl_dbsync.go
vendor/github.com/ligato/cn-infra/datasync/resync/plugin_impl_resync.go
vendor/github.com/ligato/cn-infra/flavors/etcd/etcd_flavor.go
vendor/github.com/ligato/cn-infra/flavors/etcdkafka/etcd_kafka_flavor.go
vendor/github.com/ligato/cn-infra/flavors/local/local_flavor.go
vendor/github.com/ligato/cn-infra/flavors/redis/redis_flavor.go
vendor/github.com/ligato/cn-infra/servicelabel/plugin_impl_servicelabel.go

fixed resync

---

cmd/agentctl/utils/common_utils.go
cmd/agentctl/utils/common_utils_test.go
cmd/agentctl/utils/db_utils.go

items with slash in name are shown correctly in agentctl

---

cmd/agentctl/cmd/doc.go
cmd/agentctl/utils/doc.go
cmd/doc.go
cmd/vpp-agent-ctl/main.go
cmd/vpp-agent/main.go
docker/dev_vpp_agent/README.md
idxvpp/persist/persistent_name_mapping.go
plugins/defaultplugins/aclplugin/acl_config.go
plugins/defaultplugins/aclplugin/bin_api/doc.go
plugins/defaultplugins/aclplugin/model/doc.go
plugins/defaultplugins/ifplugin/bin_api/doc.go
plugins/defaultplugins/ifplugin/model/doc.go
plugins/defaultplugins/l2plugin/bd_config.go
plugins/defaultplugins/l2plugin/bin_api/doc.go
plugins/defaultplugins/l2plugin/model/doc.go
plugins/defaultplugins/l2plugin/testing/data.go
plugins/defaultplugins/l3plugin/bin_api/doc.go
plugins/defaultplugins/l3plugin/model/doc.go
plugins/defaultplugins/l3plugin/route_config.go
plugins/linuxplugin/linuxplugin_init.go
plugins/linuxplugin/model/doc.go

Also added missing doc.go files in some packages and fixed the README in dev-vpp-agent docker.

Edited package descriptions in doc.go files. 

---

glide.yaml
plugins/defaultplugins/plugin_impl_vpp.go
vendor/github.com/ligato/cn-infra/.gitignore
vendor/github.com/ligato/cn-infra/examples/README.md
vendor/github.com/ligato/cn-infra/examples/kafka_lib/mux/main.go
vendor/github.com/ligato/cn-infra/examples/kafka_plugin/clustered/main.go
vendor/github.com/ligato/cn-infra/examples/kafka_plugin/non_clustered/main.go
vendor/github.com/ligato/cn-infra/messaging/kafka/client/config.go
vendor/github.com/ligato/cn-infra/messaging/kafka/client/messages.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/bytes_connection.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/config.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/mock.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/multiplexer.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/multiplexer_test.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/proto_connection.go
vendor/github.com/ligato/cn-infra/messaging/kafka/plugin_impl_kafka.go
vendor/github.com/ligato/cn-infra/messaging/messaging_api.go

update cn-infra (kafka)

---

glide.yaml
vendor/github.com/ligato/cn-infra/CHANGELOG.md
vendor/github.com/ligato/cn-infra/core/agent_core.go
vendor/github.com/ligato/cn-infra/core/event_loop.go
vendor/github.com/ligato/cn-infra/datasync/msgsync/plugin_impl_msgsync.go
vendor/github.com/ligato/cn-infra/examples/kafka_lib/mux/main.go
vendor/github.com/ligato/cn-infra/examples/kafka_plugin/clustered/main.go
vendor/github.com/ligato/cn-infra/examples/kafka_plugin/non_clustered/main.go
vendor/github.com/ligato/cn-infra/messaging/kafka/client/asyncproducer.go
vendor/github.com/ligato/cn-infra/messaging/kafka/client/syncproducer.go
vendor/github.com/ligato/cn-infra/messaging/kafka/doc.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/bytes_connection.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/config.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/multiplexer.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/multiplexer_test.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/proto_connection.go
vendor/github.com/ligato/cn-infra/messaging/kafka/plugin_impl_kafka.go

updated cn-infra

---

cmd/agentctl/utils/print_text.go
examples/idx_bd_cache/main.go
examples/idx_iface_cache/main.go
plugins/defaultplugins/l2plugin/bd_state.go
plugins/linuxplugin/linuxcalls/veth_linuxcalls.go
tests/go/itest/l2tst/data.go

ODPM-580: remove incorrect unicode characters from bridge domain state

---

examples/govpp_call/main.go

ODPM-569: replaced plugin dependency with appropriate interface

---

vendor/git.fd.io/govpp.git/core/core.go

delay after watchedFile is created and before connecting to the vpp

---

vendor/git.fd.io/govpp.git/core/core.go

govpp delay is configurable using -delay=xx parameter

---

docker/dev_vpp_agent/Dockerfile
docker/dev_vpp_agent/supervisord.conf
docker/prod_vpp_agent/Dockerfile
docker/prod_vpp_agent/supervisord.conf
tests/perf/download-images.sh
tests/perf/remove-pods.sh
tests/perf/timemeasure.sh
tests/perf/vpp.yaml

Signed-off-by: Marcel <msestak@cisco.com>

introduced delay and changes in docker files, and supervisord.conf

---

plugins/linuxplugin/interface_config.go
plugins/linuxplugin/linuxcalls/ns_linuxcalls.go

ODPM-638: linuxplugin - work namespace to avoid collisions

---

plugins/linuxplugin/interface_config.go
plugins/linuxplugin/linuxcalls/ns_linuxcalls.go

verify namespace presence before removing

---

docker/dev_vpp_agent/README.md

Fix link to "starting the image" section.

Update dev_vpp_agent README.md

---

plugins/defaultplugins/data_change.go
plugins/defaultplugins/l3plugin/model/l3/keys_agent_l3.go
plugins/defaultplugins/l3plugin/route_config.go
plugins/defaultplugins/l3plugin/vppcalls/route_vppcalls.go

Fixed some issues with static routes in l3plugin and adding support for VRF>0.

ODPM-158: Adding support for VRF>0

---

flavors/local/local_flavor.go
flavors/rpc/rpc_flavor.go
flavors/vpp/vpp_flavor.go
plugins/linuxplugin/data_change.go
plugins/linuxplugin/data_resync.go
plugins/linuxplugin/interface_config.go
plugins/linuxplugin/linuxcalls/ns_linuxcalls.go
plugins/linuxplugin/linuxcalls/veth_linuxcalls.go
plugins/linuxplugin/linuxplugin_init.go
plugins/linuxplugin/watch_events.go

replace default logger in linuxplugin

---

docker/dev_vpp_agent/Dockerfile
docker/dev_vpp_agent/defaultplugins.conf
docker/dev_vpp_agent/linuxplugin.conf
docker/dev_vpp_agent/supervisord.conf
docker/prod_vpp_agent/Dockerfile
docker/prod_vpp_agent/defaultplugins.conf
docker/prod_vpp_agent/linuxplugin.conf
docker/prod_vpp_agent/supervisord.conf

Signed-off-by: Marcel <msestak@cisco.com>

added default and linux plugin conf files

---

.travis.yml

updated vpp submodule

---

vendor/github.com/ligato/cn-infra/CHANGELOG.md
vendor/github.com/ligato/cn-infra/core/agent_core.go
vendor/github.com/ligato/cn-infra/datasync/doc.go
vendor/github.com/ligato/cn-infra/datasync/grpcsync/doc.go
vendor/github.com/ligato/cn-infra/datasync/kvdbsync/doc.go
vendor/github.com/ligato/cn-infra/datasync/kvdbsync/local/doc.go
vendor/github.com/ligato/cn-infra/datasync/syncbase/doc.go
vendor/github.com/ligato/cn-infra/datasync/syncbase/msg/doc.go
vendor/github.com/ligato/cn-infra/docker/dev_cn_infra/README.md
vendor/github.com/ligato/cn-infra/docker/dev_cn_infra/build.sh
vendor/github.com/ligato/cn-infra/glide.yaml
vendor/github.com/ligato/cn-infra/logging/measure/stopwatch.go
vendor/github.com/ligato/cn-infra/scripts/static_analysis.sh
vendor/github.com/ligato/cn-infra/scripts/test_examples.sh

update cn-infra to version 1.0.5

---

glide.yaml

corrected cn-infra version in glide.yaml

---

plugins/defaultplugins/README.md
plugins/defaultplugins/data_resync.go
plugins/defaultplugins/defaultplugins.conf
plugins/defaultplugins/ifplugin/data_resync.go
plugins/defaultplugins/ifplugin/interface_config.go
plugins/defaultplugins/plugin_impl_vpp.go
plugins/defaultplugins/watch_events.go

ODPM-628:  resync strategies

---

tests/perf/README.md
tests/perf/timemeasure.sh
tests/perf/vpp.yaml
tests/perf/vswitch-vpp.yaml

Signed-off-by: Marcel <msestak@cisco.com>

modified profiling scripts and  yaml files

---

plugins/defaultplugins/l2plugin/vppcalls/arp_term_vppcalls.go

I removed some redundant code and removed unnecessary complicated parsing of IP address .

Cleanup code in l2plugin vppcalls

---

plugins/defaultplugins/l3plugin/vppdump/dump_vppcalls.go
plugins/defaultplugins/l3plugin/vppdump/dump_vppcalls_test.go

fix dump vpp static routes

---

plugins/defaultplugins/plugin_impl_vpp.go

fixed mtu resolution if not defined in config file

---

vendor/git.fd.io/govpp.git/core/core.go

govpp delay flag

---

CHANGELOG.md

remove deadlinks

---

docker/dev_vpp_agent/build-agent.sh

install gometalinter in build-agent script

---

docker/dev_vpp_agent/Dockerfile
tests/robot/suites/traffic/acl_traffic/acl_traffic.robot
tests/robot/suites/traffic/acl_traffic/test_data/acl_basic.conf

Vpp-agent image updated with telnet installation

---

docker/dev_vpp_agent/Dockerfile

Added netcat installation into image

---

cmd/vpp-agent-ctl/main.go
plugins/linuxplugin/data_resync.go
plugins/linuxplugin/l3plugin/l3idx/linux_l3_route_index.go
plugins/linuxplugin/l3plugin/route_config.go
plugins/linuxplugin/linuxplugin_init.go
plugins/linuxplugin/watch_events.go

ODPM-701: linux route waits until interface is configured

---

cmd/vpp-agent-ctl/main.go
examples/govpp_call/main.go
examples/idx_bd_cache/deps.go
examples/idx_bd_cache/main.go
examples/idx_iface_cache/deps.go
examples/idx_iface_cache/main.go
plugins/defaultplugins/aclplugin/acl_config.go
plugins/defaultplugins/aclplugin/data_resync.go
plugins/defaultplugins/aclplugin/model/acl/acl.pb.go
plugins/defaultplugins/aclplugin/model/acl/acl.proto
plugins/defaultplugins/aclplugin/vppcalls/acl_vppcalls.go
plugins/defaultplugins/aclplugin/vppcalls/interfaces_async_vppcalls.go
plugins/defaultplugins/aclplugin/vppdump/dump_vppcalls.go
plugins/defaultplugins/data_change.go
plugins/defaultplugins/data_resync.go
plugins/defaultplugins/plugin_api_vpp.go
plugins/defaultplugins/plugin_impl_vpp.go
plugins/linuxplugin/linuxplugin_api.go
plugins/linuxplugin/linuxplugin_init.go
tests/go/itest/iftst/then.go

 ODPM-661: finalize ACL plugin

---

plugins/defaultplugins/ifplugin/interface_config.go

 memif ringsize workaround removed

---

glide.yaml
vendor/github.com/ligato/cn-infra/CHANGELOG.md
vendor/github.com/ligato/cn-infra/datasync/kvdbsync/watch_impl.go
vendor/github.com/ligato/cn-infra/docker/dev_cn_infra/Dockerfile

update cn-infra to v1.0.7

---

CHANGELOG.md
cmd/vpp-agent-ctl/json/app-ns.json
cmd/vpp-agent-ctl/json/enable-l4.json
plugins/defaultplugins/README.md
plugins/defaultplugins/l3plugin/README.md
plugins/defaultplugins/l4plugin/README.md

update vpp-agent 1.0.8 changelog + READMEs

---

plugins/linuxplugin/ifplugin/interface_config.go

enable debug log in linuxplugin

---

tests/robot/suites/traffic/veth_afpacket_memif_vxlan_traffic/veth_afpacket_memif_vxlan_traffic.robot

added sync time in tests

---

plugins/defaultplugins/ifplugin/interface_config.go

enable debug log for defaultplugins/ifplugin

---

plugins/defaultplugins/ifplugin/interface_config.go

remove redundant log level setup

---

tests/robot/libraries/linux.py
tests/robot/suites/traffic/veth_afpacket_memif_vxlan_traffic/veth_afpacket_memif_vxlan_traffic.robot

modifiet veht_vxlan traffic tests

---

tests/robot/suites/sfc/east-west/vswitch_1x_vpp_1x_novpp/test_data/basic.conf
tests/robot/suites/sfc/east-west/vswitch_2x_vnf_vpp/test_data/basic.conf
tests/robot/suites/traffic/acl_traffic/test_data/acl_basic.conf

changed configs for sfc_tests

---

plugins/defaultplugins/ifplugin/data_resync.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls.go

do not register afpackets during resync

---

plugins/defaultplugins/ifplugin/afpacket_config.go
plugins/defaultplugins/ifplugin/interface_config.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls.go

unregister removed af-packet interface

---

tests/robot/suites/traffic/veth_afpacket_memif_vxlan_traffic/veth_afpacket_memif_vxlan_traffic.robot

fix in veth test

---

.gitignore
tests/robot/libraries/docker.robot
tests/robot/libraries/linux.robot
tests/robot/libraries/vpp_ctl.robot
tests/robot/libraries/vpp_term.robot
tests/robot/suites/crud/acl_crud.robot
tests/robot/suites/traffic/acl_traffic/acl_traffic.robot
tests/robot/suites/traffic/acl_traffic/replyACL/reply_acl1_tcp.txt
tests/robot/suites/traffic/acl_traffic/replyACL/reply_acl1_tcp_term.txt
tests/robot/suites/traffic/acl_traffic/replyACL/reply_acl3_UDP.txt
tests/robot/suites/traffic/acl_traffic/replyACL/reply_acl3_UDP_term.txt
tests/robot/suites/traffic/vpp_2novpp_memif_traffic/vpp_2novpp_memif_traffic.robot
tests/robot/variables/common_variables.robot

ACL traffic tests

---

plugins/defaultplugins/ifplugin/interface_config.go
plugins/defaultplugins/ifplugin/model/interfaces/interfaces.pb.go
plugins/defaultplugins/ifplugin/model/interfaces/interfaces.proto
plugins/defaultplugins/ifplugin/vppcalls/ip_container_vppcalls.go

Signed-off-by: Jozef Gloncak <jozef.gloncak@pantheon.tech>

Calling IP container VPP API

---

docker/dev_vpp_agent/Dockerfile
tests/robot/suites/crud/arp_crud.robot

build image with gcc7 compiler fot VPP

---

docker/dev_vpp_agent/Dockerfile
tests/robot/suites/crud/arp_crud.robot

build image with gcc7 compiler for VPP

---

plugins/defaultplugins/ifplugin/stn_config.go

Signed-off-by: Jozef Bacigal <jozef.bacigal@pantheon.tech>

Fix wrong import file in stn_config

---

plugins/defaultplugins/plugin_impl_vpp.go

fixed skip-resync parameter if no config file is provided

---

tests/robot/resources/arp.json
tests/robot/suites/crud/arp_crud.robot
tests/robot/suites/traffic/3x_vpp_traffic/3x_vpp_traffic.robot

adding sync time for 3x_vpp_traffic.robot test

---

plugins/defaultplugins/aclplugin/vppdump/dump_vppcalls.go
plugins/restplugin/README.md
plugins/restplugin/plugin_impl_rest.go
plugins/restplugin/rest_handlers.go

Added a REST API to configure an IP ACL

Expanded REST GET APIs for IP ACLs

---

plugins/defaultplugins/aclplugin/acl_config.go
plugins/defaultplugins/aclplugin/vppcalls/acl_vppcalls.go
plugins/defaultplugins/aclplugin/vppcalls/interfaces_async_vppcalls.go
plugins/defaultplugins/aclplugin/vppdump/dump_vppcalls.go
plugins/defaultplugins/plugin_api_vpp.go
plugins/defaultplugins/plugin_impl_vpp.go

fixed acl actions + acl dump mock

---

plugins/defaultplugins/ifplugin/interface_config.go
plugins/defaultplugins/plugin_impl_vpp.go

ODPM-748: remove vpp-agent default falue for MTU

---

docker/dev_vpp_agent/Dockerfile

gcc 5.4 is back

---

tests/robot/libraries/docker.robot
tests/robot/libraries/vpp_ctl.robot
tests/robot/libraries/vpp_term.robot
tests/robot/resources/app_namespace.json
tests/robot/resources/enable-l4.json
tests/robot/suites/crud/app_namespaces_crud.robot

Signed-off-by: DasaSimkova <dsimkova@cisco.com>

Add application namespaces crud test

---

plugins/defaultplugins/ifplugin/afpacket_config.go
plugins/defaultplugins/ifplugin/interface_config.go

port af_packet registration fix

---

docker/dev_vpp_agent/Dockerfile
docker/dev_vpp_agent/logs.conf
docker/dev_vpp_agent/supervisord.conf
tests/robot/suites/crud/arp_crud.robot

added logs.conf to docker image

---

plugins/defaultplugins/aclplugin/vppcalls/interfaces_async_vppcalls.go

added return value check to acl async watcher

---

plugins/defaultplugins/data_change.go
plugins/defaultplugins/watch_events.go

fix dataChangeACL return value if err != nil

---

cmd/vpp-agent-ctl/main.go
plugins/defaultplugins/aclplugin/acl_config.go
plugins/defaultplugins/ifplugin/afpacket_config.go
plugins/defaultplugins/ifplugin/bfd_config.go
plugins/defaultplugins/ifplugin/interface_config.go
plugins/defaultplugins/ifplugin/stn_config.go
plugins/defaultplugins/l2plugin/bd_config.go
plugins/defaultplugins/l2plugin/fib_config.go
plugins/defaultplugins/l2plugin/xconnect_config.go
plugins/defaultplugins/l3plugin/arp_config.go
plugins/defaultplugins/l3plugin/route_config.go
plugins/defaultplugins/l4plugin/l4_configurator.go
plugins/defaultplugins/plugin_impl_vpp.go
plugins/linuxplugin/ifplugin/interface_config.go
plugins/linuxplugin/l3plugin/arp_config.go
plugins/linuxplugin/l3plugin/route_config.go
plugins/linuxplugin/linuxplugin_init.go

consolidate logs in plugins

---

plugins/defaultplugins/l4plugin/l4_configurator.go

added interface presence validation to app ns config

---

docker/dev_vpp_agent/Dockerfile

reverted docker file

---

plugins/defaultplugins/ifplugin/afpacket_config.go
plugins/defaultplugins/ifplugin/interface_config.go
plugins/defaultplugins/watch_events.go
plugins/linuxplugin/ifplugin/interface_config.go

fix af_packet if linux interface is created/removed

---

tests/robot/libraries/configurations.robot
tests/robot/libraries/docker.robot
tests/robot/suites/traffic/veth_af_packet_traffic/test_data/veth_basic.conf
tests/robot/suites/traffic/veth_af_packet_traffic/veth_af_packet_traffic.robot
tests/robot/variables/common_variables.robot

updated veth_af_packet_traffic test

---

plugins/linuxplugin/ifplugin/interface_config.go

added logs to linuxplugin microservice handler

---

plugins/linuxplugin/ifaceidx/linux_if_index.go
plugins/linuxplugin/interface_config.go
plugins/linuxplugin/model/interfaces/interfaces.pb.go
plugins/linuxplugin/model/interfaces/interfaces.proto

port af-packet resolution if linux interface is created/removed

---

tests/robot/suites/traffic/veth_af_packet_traffic/veth_af_packet_traffic.robot

added veth traffic testaces

---

plugins/linuxplugin/ifplugin/interface_config.go

returned reset latest docker ID if list returns 404

---

tests/robot/suites/traffic/veth_af_packet_traffic/veth_af_packet_traffic.robot

fix for veht_traffic test

---

vendor/github.com/ligato/cn-infra/datasync/resync/plugin_impl_resync.go

port do resync in deterministic order

---

glide.yaml
plugins/defaultplugins/plugin_impl_vpp.go
plugins/defaultplugins/publish.go
vendor/github.com/ligato/cn-infra/health/probe/plugin_impl_probes.go
vendor/github.com/ligato/cn-infra/health/statuscheck/model/status/status.pb.go
vendor/github.com/ligato/cn-infra/health/statuscheck/model/status/status.proto
vendor/github.com/ligato/cn-infra/health/statuscheck/plugin_api_statuscheck.go
vendor/github.com/ligato/cn-infra/health/statuscheck/plugin_impl_statuscheck.go

depends on https://github.com/ligato/cn-infra/pull/227

ODPM-642: "push" interface state data to statuscheck readiness probe

---

tests/robot/libraries/configurations.robot
tests/robot/libraries/vpp_term.robot
tests/robot/suites/traffic/veth_af_packet_traffic/test_data/veth_basic.conf
tests/robot/suites/traffic/veth_af_packet_traffic/veth_af_packet_traffic.robot

modified veth_traffic test

---

plugins/linuxplugin/data_resync.go
plugins/linuxplugin/ifplugin/interface_config.go
plugins/linuxplugin/ifplugin/linuxcalls/veth_linuxcalls.go
plugins/linuxplugin/linuxplugin_init.go
plugins/linuxplugin/watch_events.go

check veth presence and state

---

plugins/defaultplugins/plugin_impl_vpp.go
plugins/defaultplugins/publish.go

do not push status data while the defaultplugins is unregistered

---

plugins/linuxplugin/ifplugin/interface_config.go
plugins/linuxplugin/ifplugin/linuxcalls/ns_common_linuxcalls.go
plugins/linuxplugin/ifplugin/linuxcalls/ns_linuxcalls.go

- improve some log messages and add more relevant data
- move logging after mutex is locked
- split long lines to multiple lines and remove some useless code

Improve logging

---

tests/robot/suites/api/management_api/management_api.robot
tests/robot/suites/crud/linux_ip_route_crud.robot

fixed failing tests

---

tests/robot/suites/api/management_api/management_api.robot

fixed management_api test

---

glide.yaml
plugins/defaultplugins/publish.go
vendor/github.com/ligato/cn-infra/datasync/syncbase/watcher.go
vendor/github.com/ligato/cn-infra/examples/kafka-lib/asyncproducer/asyncproducer.go
vendor/github.com/ligato/cn-infra/examples/kafka-lib/consumer/consumer.go
vendor/github.com/ligato/cn-infra/examples/kafka-lib/mux/main.go
vendor/github.com/ligato/cn-infra/examples/kafka-lib/syncproducer/syncproducer.go
vendor/github.com/ligato/cn-infra/messaging/kafka/client/asyncproducer.go
vendor/github.com/ligato/cn-infra/messaging/kafka/client/config.go
vendor/github.com/ligato/cn-infra/messaging/kafka/client/consumer.go
vendor/github.com/ligato/cn-infra/messaging/kafka/client/syncproducer.go
vendor/github.com/ligato/cn-infra/messaging/kafka/mux/config.go
vendor/github.com/ligato/cn-infra/messaging/kafka/plugin_impl_kafka.go
vendor/github.com/ligato/cn-infra/utils/clienttls/doc.go
vendor/github.com/ligato/cn-infra/utils/clienttls/tlsutil.go

prevent repeating the same error while publishing interface state

---

tests/robot/suites/traffic/linux_traffic/1x_vpp_3x_namespaces_traffic.robot

linux_traffic test modified

---

tests/robot/suites/traffic/3x_vpp_traffic/3x_vpp_traffic.robot

fixed failed tests

---

tests/robot/suites/traffic/3x_vpp_traffic/3x_vpp_traffic_simple.robot

simple 3x_vpp_traffic tests

---

tests/robot/suites/traffic/3x_vpp_traffic/3x_vpp_traffic_simple.robot

modified 3_vpp_traffic_simple test

---

plugins/defaultplugins/publish.go

publish if state events compares errors as strings

---

tests/robot/libraries/vpp_ctl.robot
tests/robot/resources/arp_linux.json
tests/robot/resources/arp_linux_ns.json
tests/robot/suites/crud/arp_crud.robot
tests/robot/suites/crud/linux_arp_crud.robot
tests/robot/suites/traffic/3x_vpp_traffic/3x_vpp_traffic_simple.robot
tests/robot/suites/traffic/veth_af_packet_traffic/veth_af_packet_traffic_simple.robot

few test fixes

---

cmd/vpp-agent-ctl/json/arp-linux.json

added example json for linux arp

---

CHANGELOG.md
glide.yaml
vendor/github.com/ligato/cn-infra/CHANGELOG.md
vendor/github.com/ligato/cn-infra/Makefile
vendor/github.com/ligato/cn-infra/examples/statuscheck-plugin/Readme.md
vendor/github.com/ligato/cn-infra/examples/statuscheck-plugin/doc.go
vendor/github.com/ligato/cn-infra/examples/statuscheck-plugin/etcd.conf
vendor/github.com/ligato/cn-infra/examples/statuscheck-plugin/main.go

changlog for next release

---

tests/robot/libraries/vpp_ctl.robot
tests/robot/libraries/vpp_term.robot
tests/robot/resources/tapv2_interface_with_ip.json
tests/robot/suites/crud/tapv2_crud.robot
tests/robot/suites/traffic/l2xconnect_traffic/l2xconnect_trafic.robot
tests/robot/suites/traffic/tapv2_int_traffic/tapv2_int_and_route_config_order_traffic.robot
tests/robot/suites/traffic/tapv2_int_traffic/tapv2_int_traffic.robot

l2xconnect and tapv2 testcases

---

plugins/defaultplugins/l4plugin/data_resync.go
plugins/defaultplugins/l4plugin/l4_configurator.go

minor l4plugin refactor

---

plugins/defaultplugins/l3plugin/data_resync.go

l3plugin resync refactored

---

cmd/vpp-agent-ctl/main.go
plugins/defaultplugins/ifplugin/vppdump/dump_vppcalls.go
plugins/defaultplugins/l2plugin/bd_config.go
plugins/defaultplugins/l2plugin/bd_state.go
plugins/defaultplugins/l2plugin/bdidx/bd_index.go
plugins/defaultplugins/l2plugin/bdidx/bd_index_test.go
plugins/defaultplugins/l2plugin/data_resync.go
plugins/defaultplugins/l2plugin/fib_config.go
plugins/defaultplugins/l2plugin/vppcalls/bridge_domain_vppcalls.go
plugins/defaultplugins/l2plugin/vppcalls/bridge_domain_vppcalls_test.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls_test.go
plugins/defaultplugins/plugin_impl_vpp.go

l2plugin resync refactored

---

plugins/defaultplugins/ifplugin/afpacket_config.go
plugins/defaultplugins/ifplugin/bfd_config.go
plugins/defaultplugins/ifplugin/data_resync.go
plugins/defaultplugins/ifplugin/interface_config.go
plugins/defaultplugins/ifplugin/interface_state.go
plugins/defaultplugins/ifplugin/stn_config.go
plugins/defaultplugins/ifplugin/vppcalls/bfd_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/bfd_vppcalls_test.go
plugins/defaultplugins/ifplugin/vppcalls/stn_vppcalls.go

ifplugin resync refactored

---

plugins/defaultplugins/l2plugin/bd_config.go
plugins/defaultplugins/l2plugin/bdidx/bd_index.go

fixed nil pointer if new interface is created in l2plugin

---

plugins/defaultplugins/l2plugin/bdidx/bd_index_test.go

fixed unstable bridge domain test

---

plugins/linuxplugin/l3plugin/arp_config.go
plugins/linuxplugin/watch_events.go

Linux ARP configurator reacts on linux interface add/del changes

---

plugins/defaultplugins/l2plugin/bd_config.go

fixed bd update if old and new config have no bvi set

---

Makefile

added linux plugins to make generate

---

plugins/linuxplugin/ifplugin/interface_config.go
plugins/linuxplugin/l3plugin/arp_config.go
plugins/linuxplugin/l3plugin/route_config.go

added new model paths to go generate in linuxplugin

---

plugins/defaultplugins/aclplugin/vppcalls/acl_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/admin_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/afpacket_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/bfd_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/ip_container_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/ip_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/loopback_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/mac_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/memif_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/mtu_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/rx_mode_vppcals.go
plugins/defaultplugins/ifplugin/vppcalls/stn_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/tap_vppcals.go
plugins/defaultplugins/ifplugin/vppcalls/vxlan_vppcalls.go
plugins/defaultplugins/l2plugin/vppcalls/bridge_domain_vppcalls.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls.go
plugins/defaultplugins/l2plugin/vppcalls/l2fib_vppcalls.go
plugins/defaultplugins/l2plugin/vppcalls/xconnect_vppcalls.go
plugins/defaultplugins/l3plugin/vppcalls/arp_vppcalls.go
plugins/defaultplugins/l3plugin/vppcalls/route_vppcalls.go
plugins/defaultplugins/l4plugin/vppcalls/app_namespace_vppcalls.go
plugins/defaultplugins/l4plugin/vppcalls/features_vppcalls.go

**aclplugin**
**ifplugin**
**l3plugin**

IPv6 support

---

cmd/vpp-agent-ctl/main.go
plugins/defaultplugins/ifplugin/afpacket_config.go
plugins/defaultplugins/ifplugin/data_resync.go
plugins/defaultplugins/ifplugin/interface_config.go
plugins/defaultplugins/ifplugin/vppcalls/admin_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/afpacket_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/afpacket_vppcalls_test.go
plugins/defaultplugins/ifplugin/vppcalls/ip_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/loopback_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/memif_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/tap_vppcals.go
plugins/defaultplugins/ifplugin/vppcalls/vxlan_vppcalls.go
plugins/defaultplugins/ifplugin/vppdump/dump_vppcalls.go
plugins/defaultplugins/watch_events.go
plugins/linuxplugin/ifplugin/interface_config.go
plugins/linuxplugin/ifplugin/interface_state.go
plugins/linuxplugin/ifplugin/linuxcalls/ip_linuxcalls.go
plugins/linuxplugin/ifplugin/linuxcalls/ns_linuxcalls.go

resync and tap handling improvements

---

cmd/vpp-agent-ctl/json/stn-rule.json
cmd/vpp-agent-ctl/main.go
plugins/defaultplugins/ifplugin/stn_config.go

- stn rule do not fail if ip address is set with mask
- corrected json file

stn ip address resolution

---

tests/robot/libraries/vpp_ctl.robot
tests/robot/resources/tap_interface_unnumbered.json
tests/robot/suites/crud/tap_unnumbered_crud.robot

Signed-off-by: Patrik Hrnciar <patrik.hrnciar@gmail.com>

Add robotframework crud test-suite for unnumbered interface

---

plugins/defaultplugins/ifplugin/data_resync.go
plugins/linuxplugin/ifplugin/data_resync.go
plugins/linuxplugin/ifplugin/interface_config.go
plugins/linuxplugin/ifplugin/linuxcalls/ip_linuxcalls.go

linux interface resync improvements

---

plugins/defaultplugins/ifplugin/vppcalls/nat_vppcalls.go

corrected nat return value log

---

plugins/linuxplugin/ifplugin/interface_config.go

set correct namespace parameter if type is microservice_ref_ns

---

docker/dev_vpp_agent/Dockerfile
docker/dev_vpp_agent/README.md
docker/dev_vpp_agent/agent_start.py
docker/dev_vpp_agent/supervisord.conf
docker/dev_vpp_agent/supervisord_kill.py
docker/prod_vpp_agent/Dockerfile
docker/prod_vpp_agent/README.md
docker/prod_vpp_agent/agent_start.py
docker/prod_vpp_agent/supervisord_kill.py

docker image improvements

---

plugins/defaultplugins/plugin_impl_vpp.go
plugins/linuxplugin/l3plugin/data_resync.go
plugins/linuxplugin/l3plugin/l3idx/linux_l3_route_index.go
plugins/linuxplugin/l3plugin/route_config.go

order by preference - link route

---

Gopkg.lock
Gopkg.toml
vendor/github.com/ligato/cn-infra/db/keyval/etcdv3/bytes_broker_impl.go
vendor/github.com/ligato/cn-infra/db/keyval/etcdv3/bytes_watcher_impl.go

update cn-infra 

---

plugins/defaultplugins/watch_events.go
plugins/linuxplugin/ifplugin/data_resync.go
plugins/linuxplugin/ifplugin/ifaceidx/linux_if_index.go
plugins/linuxplugin/ifplugin/interface_config.go
plugins/linuxplugin/l3plugin/arp_config.go
plugins/linuxplugin/l3plugin/data_resync.go
plugins/linuxplugin/l3plugin/linuxcalls/ns_linuxcalls.go
plugins/linuxplugin/l3plugin/route_config.go
plugins/linuxplugin/linuxplugin_init.go

* corrected linux interface mapping indices for multiple namespaces
* linux route with gateway considers interface default routes when calculating reachability

fix linux routes

---

cmd/vpp-agent-ctl/json/dhcp.json

added dhcp json example

---

plugins/linuxplugin/l3plugin/data_resync.go

added network reachability check while reading routes with dst address

---

plugins/linuxplugin/l3plugin/route_config.go

cached linux route is correctly removed

---

tests/robot/suites/sfc/east-west/vswitch_1x_vpp_1x_novpp/vswitch_1x_vpp_1x_novpp.robot
tests/robot/suites/traffic/linux_traffic/1x_vpp_3x_namespaces_traffic.robot

fix5 for failed jenkins jobs

---

plugins/linuxplugin/l3plugin/route_config.go

fixed unreachable gw check for new interface

---

tests/robot/suites/crud/acl_crudIPv6.robot
tests/robot/suites/crud/replyACL/reply_acl1IPv6_tcp.txt
tests/robot/suites/crud/replyACL/reply_acl1IPv6_tcp_term.txt
tests/robot/suites/crud/replyACL/reply_acl1IPv6_update_tcp.txt
tests/robot/suites/crud/replyACL/reply_acl1IPv6_update_tcp_term.txt
tests/robot/suites/crud/replyACL/reply_acl2IPv6_delete_tcp_term.txt
tests/robot/suites/crud/replyACL/reply_acl2IPv6_tcp.txt
tests/robot/suites/crud/replyACL/reply_acl2IPv6_tcp_term.txt
tests/robot/suites/crud/replyACL/reply_acl3IPv6_udp.txt
tests/robot/suites/crud/replyACL/reply_acl3IPv6_udp_term.txt
tests/robot/suites/crud/replyACL/reply_acl4IPv6_udp.txt
tests/robot/suites/crud/replyACL/reply_acl4IPv6_udp_term.txt
tests/robot/suites/crud/replyACL/reply_acl5IPv6_icmp.txt
tests/robot/suites/crud/replyACL/reply_acl5IPv6_icmp_term.txt
tests/robot/suites/crud/replyACL/reply_acl6IPv6_all_term.txt
tests/robot/suites/crud/replyACL/reply_acl6IPv6_icmp.txt
tests/robot/suites/crud/replyACL/reply_acl6IPv6_icmp_term.txt
tests/robot/suites/crud/replyACL/reply_aclIPv6_all.txt
tests/robot/suites/crud/replyACL/reply_aclIPv6_all_term.txt
tests/robot/suites/crud/test_data/acl_crudIPv6.robot

acl_crud tests for ipv6

---

plugins/linuxplugin/ifplugin/data_resync.go

linux interface resync: cache interface before checking namespace

---

plugins/linuxplugin/nsplugin/ns_impl.go

fixed default namespace initialization

---

plugins/linuxplugin/ifplugin/interface_config.go

check config before removing obsolete veth peer

---

cmd/vpp-agent-ctl/main.go
plugins/defaultplugins/l2plugin/bd_config.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls_test.go

shg can be set/modified for interfaces

---

vendor/github.com/ligato/cn-infra/config/plugin_config.go
vendor/github.com/ligato/cn-infra/datasync/syncbase/watcher.go
vendor/github.com/ligato/cn-infra/db/keyval/etcdv3/README.md
vendor/github.com/ligato/cn-infra/db/keyval/etcdv3/bytes_broker_impl.go
vendor/github.com/ligato/cn-infra/db/keyval/etcdv3/config.go
vendor/github.com/ligato/cn-infra/db/keyval/etcdv3/plugin_impl_etcdv3.go

cn-infra update

---

Gopkg.lock
Gopkg.toml

updated .toml and .lock files

---

plugins/defaultplugins/ifplugin/afpacket_config.go
plugins/defaultplugins/ifplugin/data_resync.go
plugins/defaultplugins/ifplugin/interface_config.go
plugins/defaultplugins/l2plugin/vppdump/dump_vppcalls.go
plugins/linuxplugin/ifplugin/data_resync.go
plugins/linuxplugin/nsplugin/microservices.go

veth and afpacket bugfix

---

plugins/linuxplugin/l3plugin/route_config.go

fixed removal of linux static  route without gateway address

---

plugins/defaultplugins/l3plugin/data_resync.go
plugins/linuxplugin/common/model/l3/l3.proto

vpp route resync comparsion works if weight is not set

---

clientv1/defaultplugins/dbadapter/data_change_db.go
clientv1/defaultplugins/dbadapter/data_resync_db.go
clientv1/defaultplugins/grpcadapter/data_change_grpc.go
clientv1/defaultplugins/grpcadapter/data_resync_grpc.go
cmd/vpp-agent-ctl/main.go
plugins/defaultplugins/common/model/l3/l3.pb.go
plugins/defaultplugins/common/model/l3/l3.proto
plugins/defaultplugins/l3plugin/arp_proxy_config.go

fixed typo in model

---

tests/robot/libraries/vpp_term.robot
tests/robot/suites/crud/stn_rule_crud.robot
tests/robot/suites/crud/stn_rule_crudIPv6.robot
tests/robot/suites/traffic/veth_afpacket_memif_vxlan_traffic/veth_afpacket_memif_vxlan_trafficIPv6.robot
tests/robot/suites/traffic/veth_afpacket_memif_vxlan_traffic/veth_afpacket_memif_vxlan_traffic_other_vrfIPv6.robot
tests/robot/variables/ccmts_vm_variables.robot

added ipv6 tests

---

Gopkg.lock
Gopkg.toml
vendor/github.com/ligato/cn-infra/idxmap/api.go
vendor/github.com/ligato/cn-infra/idxmap/mem/inmemory_name_mapping.go

cn-infra update (b1d7b65)

---

idxvpp/api.go
idxvpp/nametoidx/inmemory_name_to_idx_mapping.go
plugins/defaultplugins/l2plugin/bd_config.go
plugins/defaultplugins/l2plugin/bdidx/bd_index.go
plugins/defaultplugins/l2plugin/bdidx/bd_index_test.go

update metadata for name-to-idx mapping

---

plugins/linuxplugin/ifplugin/data_resync.go

do not register unknown veths during resync

---

CHANGELOG.md

updated changelog for new release

---

tests/robot/libraries/docker.robot
tests/robot/suites/crud/linux_arp_crud.robot
tests/robot/suites/misc/etcd_clear.robot
tests/robot/suites/sfc/test_controller_start/controller_start.robot

fixes in tests

---

examples/README.md

update readme for examples

---

Gopkg.lock
Gopkg.toml
vendor/github.com/ligato/cn-infra/datasync/resync/plugin_impl_resync.go
vendor/github.com/ligato/cn-infra/db/keyval/etcdv3/plugin_impl_etcdv3.go
vendor/github.com/ligato/cn-infra/flavors/connectors/all_connectors_flavor.go
vendor/github.com/ligato/cn-infra/utils/addrs/ip.go

cn-infra update (461693b)

---

plugins/defaultplugins/ifplugin/vppcalls/admin_vppcalls_test.go
plugins/defaultplugins/ifplugin/vppcalls/afpacket_vppcalls_test.go
plugins/defaultplugins/ifplugin/vppcalls/bfd_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/bfd_vppcalls_test.go
plugins/defaultplugins/ifplugin/vppcalls/nat_vppcalls_test.go

vppcalls unit tests - admin, af-packet, bfd

---

plugins/defaultplugins/aclplugin/vppdump/dump_vppcalls.go
plugins/defaultplugins/ifplugin/interface_config.go
plugins/defaultplugins/ifplugin/interface_state.go
plugins/defaultplugins/ifplugin/vppdump/dump_nat_vppcalls.go
plugins/defaultplugins/ifplugin/vppdump/dump_vppcalls.go
plugins/govppmux/vppcalls/vpe_vppcalls.go

Before the fix, garbage after terminating NULL was considered as valid content.

Fix trimming zero-ended strings

---

plugins/defaultplugins/l2plugin/fib_config.go

fix for l2fib interface/bridge domain resolution

---

plugins/linuxplugin/l3plugin/linuxcalls/route_linuxcalls.go
plugins/linuxplugin/l3plugin/route_config.go

fixed scope definition for linux routes

---

plugins/restplugin/README.md
tests/robot/suites/crud/replyACL/reply_aclIPv6_all.txt
tests/robot/suites/crud/replyACL/reply_acl_all.txt
tests/robot/suites/traffic/acl_traffic/replyACL/reply_acl1_tcp.txt
tests/robot/suites/traffic/acl_traffic/replyACL/reply_acl3_UDP.txt

Fix ACL crud test and README

---

Makefile

Change prefix for echo for easier read

---

.travis.yml
README.md

Add shields.io badge for latest release

---

tests/robot/libraries/KubeAdm.robot
tests/robot/libraries/KubeCtl.robot
tests/robot/libraries/KubeEnv.robot
tests/robot/libraries/KubeEnvConnections.robot
tests/robot/libraries/SshCommons.robot
tests/robot/libraries/setup-teardown.robot
tests/robot/resources/k8-yaml/etcd_k8.yaml
tests/robot/resources/k8-yaml/kafka-k8.yaml
tests/robot/resources/k8-yaml/sfc-k8.yaml
tests/robot/resources/k8-yaml/vnf-k8-agent-cfg.yaml
tests/robot/resources/k8-yaml/vnf-k8-vpp-cfg.yaml
tests/robot/resources/k8-yaml/vnf-k8.yaml
tests/robot/resources/k8-yaml/vswitch-k8.yaml
tests/robot/suites/integration/ccmts/simple_topo_restarts.robot
tests/robot/variables/jozo_local_variables.robot

add initial basic K8 support for testing

---

tests/robot/resources/k8-yaml/vswitch-k8.yaml

switch.yaml

---

tests/robot/resources/k8-yaml/dev-cn-infra-k8.yaml
tests/robot/resources/k8-yaml/vswitch-k8.yaml

changed and added yaml files

---

plugins/defaultplugins/ifplugin/stn_config.go
plugins/defaultplugins/ifplugin/vppcalls/stn_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/stn_vppcalls_test.go
plugins/defaultplugins/ifplugin/vppcalls/tap_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/tap_vppcalls_test.go
plugins/defaultplugins/ifplugin/vppcalls/vrf_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/vrf_vppcalls_test.go
plugins/defaultplugins/ifplugin/vppcalls/vxlan_vppcalls_test.go
plugins/defaultplugins/ifplugin/vppdump/dump_stn_vppcalls.go

added even more unit tests to ifplugin vppcalls

---

tests/robot/libraries/KubeEnv.robot
tests/robot/libraries/KubeEnvConnections.robot
tests/robot/libraries/setup-teardown.robot
tests/robot/resources/k8-scripts/pull-images.sh
tests/robot/resources/k8-yaml/dev-cn-infra-k8.yaml
tests/robot/suites/integration/ccmts/simple_topo_restarts.robot
tests/robot/variables/common_variables.robot

more basic kubernetes tests code

---

plugins/defaultplugins/ifplugin/interface_config.go
plugins/defaultplugins/ifplugin/interface_config_test.go
plugins/defaultplugins/ifplugin/vppcalls/rx_mode_vppcalls.go
plugins/defaultplugins/ifplugin/vppcalls/rx_mode_vppcalls_test.go

add test cases for vpp interface plugin

---

plugins/defaultplugins/ifplugin/interface_state.go

Fix incorrect logical name in ifstate notifcations

---

.gitmodules
docker/dev_vpp_agent/Dockerfile

Change url of vpp submodule and clone url in Dockerfile

---

Makefile
plugins/defaultplugins/aclplugin/acl_config.go
plugins/defaultplugins/aclplugin/acl_config_test.go
plugins/defaultplugins/aclplugin/data_resync.go
plugins/defaultplugins/aclplugin/vppcalls/acl_vppcalls.go
plugins/defaultplugins/aclplugin/vppcalls/vpp_channel.go
plugins/defaultplugins/aclplugin/vppdump/dump_vppcalls.go
plugins/defaultplugins/aclplugin/vppdump/dump_vppcalls_test.go
plugins/defaultplugins/data_resync.go
plugins/defaultplugins/ifplugin/nat_config.go
plugins/defaultplugins/ifplugin/vppdump/dump_nat_vppcalls.go
plugins/defaultplugins/ifplugin/vppdump/dump_nat_vppcalls_test.go

- fixed DisableResync from defaultplugins (https://github.com/ligato/vpp-agent/pull/588)
- minor bug fixes in the ACL plugin (https://github.com/ligato/vpp-agent/pull/589)
- performance improvements for the ACL plugin: ModifyACL calculates diff between the currently and the previously assigned interfaces and applies only the minimal number of changes necessary (https://github.com/ligato/vpp-agent/pull/589)
- bug fixes in the ifplugin/NAT (https://github.com/ligato/vpp-agent/pull/594)

Bug fixes from the Contiv branch

---

plugins/defaultplugins/common/bin_api/nat/nat.go

Move to the latest VPP version

---

Gopkg.lock
Gopkg.toml
vendor/github.com/ligato/cn-infra/db/keyval/etcdv3/bytes_broker_impl.go

[contiv] Update cn-infra revision.

---

cmd/vpp-agent-ctl/data_cmd.go
plugins/defaultplugins/l2plugin/bd_config.go
plugins/defaultplugins/l2plugin/data_resync.go
plugins/defaultplugins/l2plugin/l2idx/bd_index.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls_test.go

* simplified interface-related vppcalls in l2plugin
* added test cases

fixed shg if interface is created after bridge domain

---

plugins/defaultplugins/ifplugin/vppcalls/vxlan_vppcalls.go

fill 'instance' for vxlan api call

---

tests/robot/resources/acl_ICMP.json
tests/robot/resources/acl_MACIP.json
tests/robot/resources/acl_TCP.json
tests/robot/resources/acl_UDP.json
tests/robot/suites/crud/replyACL/reply_acl4_udp.txt

more fixes for acl tests

---

plugins/defaultplugins/ifplugin/ifaceidx/dhcp_index_test.go
plugins/defaultplugins/ifplugin/ifaceidx/sw_if_index_test.go
plugins/defaultplugins/ifplugin/vppdump/dump_vppcalls_test.go

- Add unit tests for ifaceidx/sw_if_index
- Add unit tests for ifaceidx/dhcp_index
- Add unit tests for ifplugin/vppdump/dump_vppcalls

Add unit tests for vpp/ifplugin: ifaceidx + vppdump

---

docker/dev_vpp_agent/Dockerfile
docker/prod_vpp_agent/Dockerfile
tests/robot/suites/crud/l2xconnect_crud.robot
tests/robot/suites/crud/loopback_crud.robot

fixed tests for release

---

plugins/defaultplugins/ifplugin/interface_state.go

Fix processing VPP interface stats combined counters

---

idxvpp/api.go
plugins/defaultplugins/l2plugin/bd_config.go
plugins/defaultplugins/l2plugin/data_resync.go
plugins/defaultplugins/l2plugin/fib_config.go
plugins/defaultplugins/l2plugin/l2idx/bd_index.go
plugins/defaultplugins/l2plugin/l2idx/bd_index_test.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls.go
plugins/defaultplugins/l2plugin/vppcalls/interface_vppcalls_test.go
plugins/defaultplugins/watch_events.go

depends on https://github.com/ligato/vpp-agent/pull/628
tests https://github.com/ligato/vpp-agent/pull/630

fixed fib resolution case where interface and bridge domain are not tied

---

plugins/defaultplugins/l2plugin/fib_config_test.go
plugins/defaultplugins/l2plugin/xconnect_config_test.go

depends  on https://github.com/ligato/vpp-agent/pull/629

added unit tests for fib configurator

---

CHANGELOG.md
Gopkg.lock
Gopkg.toml

updated changelog

---

plugins/defaultplugins/ifplugin/interface_state.go
plugins/defaultplugins/ifplugin/interface_state_test.go

Add unit tests for vpp/ifplugin/interface_state

---

Gopkg.lock
Gopkg.toml
vendor/github.com/ligato/cn-infra/rpc/grpc/config.go
vendor/github.com/ligato/cn-infra/rpc/grpc/listen_and_serve.go

newest cn-infra

---

plugins/vpp/ifplugin/interface_state_test.go

Fix occasional fail of test of combined stats from VPP

---

Makefile
plugins/govppmux/vppcalls/vpe_vppcalls_test.go
plugins/vpp/ifplugin/ifaceidx/dhcp_index_test.go

Cleanup unit tests in Makefile and fix issues

---

plugins/vpp/ifplugin/interface_config_test.go

Fix occasional fail of unit test

---

plugins/linux/ifplugin/README.md

fixed failing link

---

docker/dev/build.sh
docker/prod/build.sh
docker/prod/supervisord.conf
tests/perf/vpp.yaml
tests/perf/vswitch-vpp.yaml
tests/robot/resources/k8-yaml/vswitch-k8.yaml

support for docker  to build images under  proxy env

---

plugins/linux/ifplugin/README.md
plugins/vpp/l2plugin/l2idx/cache_bd_test.go
plugins/vpp/l2plugin/l2idx/fib_index_test.go
plugins/vpp/l2plugin/l2idx/xc_index_test.go

- Add l2plugin/l2idx/fib_index unit test
- Add l2plugin/l2idx/cache_bd unit test
- Add l2plugin/l2idx/fib_index unit test
- Fix dead link to m/i/interfaces.proto in linux if
Signed-off-by: Tomas Slusny tslusny@cisco.com

Add unit tests for l2plugin/l2idx

---

plugins/vpp/ifplugin/data_resync_test.go

Add unit tests for ifplugin/data_resync

---

plugins/vpp/aclplugin/aclidx/aclidx.go
plugins/vpp/aclplugin/aclidx/aclidx_test.go

Added acl-plugin aclidx unit tests

---

vpp.env

https://gerrit.fd.io/r/gitweb?p=vpp.git;a=commit;h=2302d0dfa27a348d96a6c9a7d667bd910280a098

Upgrade VPP to latest 18.04 stable

---

tests/robot/variables/jmedved_variables.robot

add variables for Jmedved Jenkins

---

plugins/vpp/l2plugin/bd_config_test.go
plugins/vpp/l2plugin/bd_state_test.go

- Add unit tests for l2plugin/bd_state
- Add unit tests for l2plugin/bd_config

Add unit tests for l2plugin/bd_state and l2plugin/bd_config

---

clientv1/linux/dbadapter/data_change_db.go

correct key for linux interface in local client

---

tests/robot/libraries/SshCommons.robot
tests/robot/libraries/docker.robot
tests/robot/libraries/setup-teardown.robot
tests/robot/libraries/ssh.robot
tests/robot/libraries/vpp.robot
tests/robot/variables/common_variables.robot

added support for whole suite results logs

---

plugins/vpp/l3plugin/vppcalls/arp_vppcalls.go
plugins/vpp/l3plugin/vppcalls/arp_vppcalls_test.go
plugins/vpp/l3plugin/vppcalls/proxyarp_vppcalls.go
plugins/vpp/l3plugin/vppcalls/proxyarp_vppcalls_test.go
plugins/vpp/l3plugin/vppcalls/route_vppcalls.go
plugins/vpp/l3plugin/vppcalls/route_vppcalls_test.go
plugins/vpp/l3plugin/vppcalls/vpp_channel.go
plugins/vpp/l3plugin/vppdump/dump_vppcalls.go
plugins/vpp/l3plugin/vppdump/dump_vppcalls_test.go

Added l3plugin vppcalls+vppdump unit tests

---

Gopkg.lock
Gopkg.toml
vendor/git.fd.io/govpp.git/core/core.go
vendor/git.fd.io/govpp.git/core/request_handler.go

Update GoVPP with improved handling of probes on timeouts

---

.gitmodules
docker/dev_vpp_agent/Dockerfile
docker/dev_vpp_agent/build.sh
vpp.env

Remove vpp git submodule (in master)

---

plugins/vpp/l3plugin/l3idx/l3_arp_index_test.go
plugins/vpp/l3plugin/l3idx/l3_route_index_test.go

Added l3plugin l3idx unit tests

---

plugins/vpp/ifplugin/nat_config.go
plugins/vpp/ifplugin/nat_config_test.go

fixed nat44 address pool resolution

---

plugins/vpp/l3plugin/arp_config.go
plugins/vpp/l3plugin/arp_config_test.go
plugins/vpp/l3plugin/arp_proxy_config.go
plugins/vpp/l3plugin/arp_proxy_config_test.go

Added l3plugin arp_config & arp_proxy_config unit tests

---

plugins/linux/ifplugin/linuxcalls/link_linuxcalls.go

Fix method for linux interface renaming.

---

plugins/linux/linuxplugin.conf
plugins/linux/linuxplugin_init.go

Make linuxplugin optional (disable via config)

---

plugins/vpp/l3plugin/route_config.go
plugins/vpp/l3plugin/route_config_test.go

Added l3plugin route-config unit tests

---

plugins/vpp/l2plugin/bd_state.go

This was occasionally causing panic after `plugin.notificationChan` was closed during shutdown.

Fix nil pointer access and check if channel has closed

---

plugins/vpp/ifplugin/afpacket_config.go

When syncing do not clear linux host interface mapping.

Fix afpacket resync

---

tests/robot/resources/k8-yaml/vnf-vpp.yaml
tests/robot/resources/k8-yaml/vswitch-deployment.yaml

Fix vpp-agent cmdline in integration tests

---

tests/robot/libraries/kubernetes/KubeEnv.robot
tests/robot/libraries/kubernetes/KubeSetup.robot
tests/robot/libraries/kubernetes/Restarts_Setup.robot
tests/robot/resources/k8-scripts/pull-images.sh
tests/robot/resources/k8-yaml/novpp.yaml
tests/robot/resources/k8-yaml/sfc-k8.yaml
tests/robot/resources/k8-yaml/vnf-vpp.yaml
tests/robot/resources/k8-yaml/vswitch-deployment.yaml
tests/robot/suites/integration/restarts/basic_restarts.robot

Pull all Docker images before integration test run

---

tests/robot/libraries/kubernetes/KubeEnv.robot

Workaround vppctl returning code 141 in integration tests

---

Gopkg.lock
Gopkg.toml
plugins/vpp/aclplugin/acl_config_test.go
plugins/vpp/aclplugin/vppdump/dump_vppcalls_test.go
plugins/vpp/ifplugin/bfd_config_test.go
plugins/vpp/ifplugin/interface_config_test.go
plugins/vpp/ifplugin/vppcalls/bfd_vppcalls_test.go
plugins/vpp/l2plugin/vppdump/dump_vppcalls_test.go
vendor/git.fd.io/govpp.git/adapter/adapter.go
vendor/git.fd.io/govpp.git/adapter/mock/mock_adapter.go
vendor/git.fd.io/govpp.git/adapter/vppapiclient/empty_adapter.go
vendor/git.fd.io/govpp.git/adapter/vppapiclient/vppapiclient_adapter.go
vendor/git.fd.io/govpp.git/api/api.go
vendor/git.fd.io/govpp.git/core/core.go
vendor/git.fd.io/govpp.git/core/request_handler.go

See https://gerrit.fd.io/r/#/c/13210/ & https://gerrit.fd.io/r/#/c/13244/

Update govpp to include sequencing of vpp requests.

---

tests/robot/suites/trafficIPv6/bridge_domain/test2_bridge_domainIPv6.robot
tests/robot/suites/trafficIPv6/bridge_domain/test3_bridge_domainIPv6.robot

fixes for ipv6 tests

---

tests/robot/libraries/linux.py
tests/robot/libraries/vpp_ctl.py
tests/robot/suites/trafficIPv6/tap_int_traffic/tap_int_and_route_config_order_trafficIPv6.robot
tests/robot/suites/trafficIPv6/tap_int_traffic/tap_int_trafficIPv6.robot
tests/robot/suites/trafficIPv6/veth_af_packet_traffic/veth_af_packet_trafficIPv6.robot

fixes to ipv6 tests

---

tests/robot/libraries/kubernetes/Restarts_Setup.robot
tests/robot/variables/ccmts_vm_variables.robot
tests/robot/variables/common_variables.robot

Fix missing default value for test variable vnf_image_name

---

tests/robot/libraries/kubernetes/KubeTestOperations.robot
tests/robot/libraries/kubernetes/kube_config_gen.py

Bugfixes for integration test

---

.gitignore
.travis.yml
Makefile
docker/dev/Dockerfile
docker/dev/build.sh
scripts/genjsonapi.sh

- decrease image size (~9.6GB+ to ~4.5GB) 
and cleanup obsolete parts
- improve Makefile and add missing parts
- cleanup .gitignore and ignore vpp folder
- other minor enhancements

Optimize dev docker image 

---

plugins/govppmux/govpp.conf
plugins/linux/linuxplugin.conf
plugins/vpp/vpp-plugin.conf

use default values in example config files

---

plugins/telemetry/config.go
plugins/telemetry/telemetry.conf
plugins/telemetry/telemetry.go

added config file for telemetry plugin

---

CHANGELOG.md
plugins/telemetry/README.md

Release vpp-agent v1.5.1

---

plugins/vpp/ifplugin/vppcalls/nat_vppcalls.go

Fix incorrect setting of VRF in handleNat44IdentityMapping

---

plugins/govppmux/govpp.conf
plugins/govppmux/govpp_channel.go
plugins/govppmux/plugin_impl_govppmux.go

retry binary api request if vpp disconnects

---

CHANGELOG.md
Gopkg.lock
Gopkg.toml
vendor/github.com/ligato/cn-infra/db/keyval/consul/consul.go

v1.5.2 changelog + cn-infra 1.4.1

---

plugins/rest/rest_handlers.go
plugins/vpp/l2plugin/bd_config.go
plugins/vpp/l2plugin/bd_config_test.go
plugins/vpp/l2plugin/data_resync.go
plugins/vpp/l2plugin/fib_config.go
plugins/vpp/l2plugin/vppcalls/api_vppcalls.go
plugins/vpp/l2plugin/vppcalls/arp_term_vppcalls.go
plugins/vpp/l2plugin/vppcalls/arp_term_vppcalls_test.go
plugins/vpp/l2plugin/vppcalls/bridge_domain_vppcalls.go
plugins/vpp/l2plugin/vppcalls/bridge_domain_vppcalls_test.go
plugins/vpp/l2plugin/vppcalls/doc.go
plugins/vpp/l2plugin/vppcalls/dump_vppcalls.go
plugins/vpp/l2plugin/vppcalls/dump_vppcalls_test.go
plugins/vpp/l2plugin/vppcalls/interface_vppcalls.go
plugins/vpp/l2plugin/vppcalls/interface_vppcalls_test.go
plugins/vpp/l2plugin/vppcalls/l2fib_vppcalls.go
plugins/vpp/l2plugin/vppcalls/l2fib_vppcalls_test.go
plugins/vpp/l2plugin/vppcalls/xconnect_vppcalls.go
plugins/vpp/l2plugin/vppcalls/xconnect_vppcalls_test.go
plugins/vpp/l2plugin/vppdump/doc.go
plugins/vpp/l2plugin/xconnect_config.go
plugins/vpp/plugin_impl_vpp.go

vppcalls api: vpp/l2plugin

---

plugins/vpp/l4plugin/appns_config.go
plugins/vpp/l4plugin/vppcalls/api_vppcalls.go
plugins/vpp/l4plugin/vppcalls/app_namespace_vppcalls.go
plugins/vpp/l4plugin/vppcalls/features_vppcalls.go

vppcalls api: vpp/l4plugin

---

plugins/vpp/ifplugin/vppcalls/api_vppcalls.go
plugins/vpp/ipsecplugin/ipsec_config.go
plugins/vpp/ipsecplugin/vppcalls/api_vppcalls.go
plugins/vpp/ipsecplugin/vppcalls/ipsec_vppcalls.go

vppcalls api: vpp/ipsec

---

plugins/rest/rest_handlers.go
plugins/vpp/l3plugin/arp_config.go
plugins/vpp/l3plugin/arp_proxy_config.go
plugins/vpp/l3plugin/data_resync.go
plugins/vpp/l3plugin/route_config.go
plugins/vpp/l3plugin/vppcalls/api_vppcalls.go
plugins/vpp/l3plugin/vppcalls/arp_vppcalls.go
plugins/vpp/l3plugin/vppcalls/arp_vppcalls_test.go
plugins/vpp/l3plugin/vppcalls/doc.go
plugins/vpp/l3plugin/vppcalls/dump_vppcalls.go
plugins/vpp/l3plugin/vppcalls/dump_vppcalls_test.go
plugins/vpp/l3plugin/vppcalls/proxyarp_vppcalls.go
plugins/vpp/l3plugin/vppcalls/proxyarp_vppcalls_test.go
plugins/vpp/l3plugin/vppcalls/route_vppcalls.go
plugins/vpp/l3plugin/vppcalls/route_vppcalls_test.go
plugins/vpp/l3plugin/vppdump/doc.go

vppcalls api: vpp/l3plugin

---

Makefile

Use specific version of markdown-link-check because latest is broken

---

plugins/vpp/ifplugin/vppcalls/compat_vppcalls.go
plugins/vpp/plugin_impl_vpp.go
plugins/vpp/srplugin/data_resync.go
plugins/vpp/srplugin/srv6_config.go
plugins/vpp/srplugin/srv6_config_test.go
plugins/vpp/srplugin/vppcalls/api_vppcalls.go
plugins/vpp/srplugin/vppcalls/srv6.go
plugins/vpp/srplugin/vppcalls/srv6_test.go
tests/vppcallfake/srv6calls.go

vppcalls api: vpp/srplugin

---

examples/govpp_call/deps.go
examples/govpp_call/main.go
examples/grpc_vpp/notifications/main.go
examples/grpc_vpp/remote_client/main.go
examples/idx_bd_cache/deps.go
examples/idx_bd_cache/main.go
examples/idx_iface_cache/deps.go
examples/idx_iface_cache/main.go
examples/idx_mapping_lookup/deps.go
examples/idx_mapping_lookup/main.go
examples/idx_mapping_watcher/deps.go
examples/idx_mapping_watcher/main.go
examples/idx_veth_cache/deps.go
examples/idx_veth_cache/main.go
examples/localclient_linux/tap/main.go
examples/localclient_linux/veth/main.go
examples/localclient_vpp/nat/main.go
examples/localclient_vpp/plugins/main.go

comment out examples to enable build

---

app/vpp_agent.go
plugins/vpp/data_resync.go
plugins/vpp/plugin_impl_vpp.go

fix plugin loading order

---

plugins/vpp/ifplugin/vppcalls/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/dump_interface_vppcalls_test.go

dhcp support added to interface dump

---

docker/dev/Dockerfile
docker/dev/build.sh
docker/prod/Dockerfile

Use Ubuntu 18.04 as base for docker image

---

app/vpp_agent.go

added probe plugin to enable liveness/readiness

---

Gopkg.lock
Gopkg.toml
vendor/git.fd.io/govpp.git/codec/msg_codec.go
vendor/git.fd.io/govpp.git/core/notification_handler.go

Update GoVPP with fix for decoding other type of notification messages

---

Gopkg.lock
Gopkg.toml
vendor/git.fd.io/govpp.git/codec/msg_codec.go
vendor/git.fd.io/govpp.git/core/notification_handler.go

[contiv-1807] Update GoVPP with fix for decoding other type of notification messages

---

plugins/linux/options.go
plugins/vpp/options.go

Use short names for linux/vpp plugins with "-plugin" suffix for conf files

---

tests/robot/libraries/vpp_term.robot

- using telnet has issue with latest VPP and replies only after sending 3 characters
- this PR switches to using vppctl instead of telnet where this issue does not occur

Fix issue with VPP CLI in robot tests

---

plugins/vpp/ifplugin/interface_config.go
plugins/vpp/ifplugin/vppcalls/api_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vxlan_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vxlan_vppcalls_test.go

fixed vxlan delete for entries with vrf != 0

---

tests/robot/libraries/basic_operations.py
tests/robot/libraries/vpp_term.robot

Fix Bug with new line

---

plugins/vpp/l3plugin/data_resync.go

fixed route resync resolution for zero next hop IP

---

plugins/vpp/data_change.go
plugins/vpp/data_resync.go
plugins/vpp/l2plugin/bd_config.go
plugins/vpp/l2plugin/bd_config_test.go
plugins/vpp/l2plugin/bd_state.go
plugins/vpp/l2plugin/bd_state_test.go
plugins/vpp/l2plugin/data_resync.go
plugins/vpp/l2plugin/fib_config.go
plugins/vpp/l2plugin/xconnect_config.go
plugins/vpp/plugin_impl_vpp.go
plugins/vpp/watch_events.go

l2-plugin: logs & errors

---

plugins/vpp/aclplugin/acl_config.go
plugins/vpp/aclplugin/acl_config_test.go
plugins/vpp/aclplugin/data_resync.go
plugins/vpp/data_change.go
plugins/vpp/data_resync.go
plugins/vpp/plugin_impl_vpp.go
plugins/vpp/watch_events.go

acl-plugin: logs & errors

---

plugins/vpp/data_change.go
plugins/vpp/data_resync.go
plugins/vpp/ipsecplugin/data_resync.go
plugins/vpp/ipsecplugin/ipsec_config.go
plugins/vpp/plugin_impl_vpp.go
plugins/vpp/watch_events.go

ipsec-plugin: logs & errors

---

plugins/vpp/data_change.go
plugins/vpp/data_resync.go
plugins/vpp/plugin_impl_vpp.go
plugins/vpp/srplugin/data_resync.go
plugins/vpp/srplugin/srv6_config.go

sr-plugin: logs & errors

---

plugins/linux/ifplugin/data_resync.go
plugins/linux/ifplugin/interface_config.go
plugins/linux/l3plugin/arp_config.go

fix linter

---

plugins/linux/ifplugin/interface_config.go

fix linux tap host/temp name

---

plugins/vpp/aclplugin/acl_config.go

corrected some logs in acl plugin

---

Gopkg.lock
vendor/github.com/ligato/cn-infra/rpc/grpc/plugin_impl_grpc.go

Update cn-infra to fix GRPC initialization when plugin is disabled

---

tests/robot/suites/crudIPv6/ip_route_crudIPv6.robot
tests/robot/suites/crudIPv6/veth_crudIPv6.robot

Fix IPv6 traffic test

---

tests/robot/suites/crud/linux_arp_crud.robot

Fix 'lo' change in Ubuntu

---

plugins/govppmux/options.go
plugins/vpp/l2plugin/bd_config.go
plugins/vpp/l2plugin/bd_config_test.go
plugins/vpp/l2plugin/fib_config.go
plugins/vpp/l2plugin/l2idx/bd_index.go
plugins/vpp/l2plugin/l2idx/bd_index_test.go
plugins/vpp/l2plugin/vppcalls/api_vppcalls.go
plugins/vpp/l2plugin/vppcalls/interface_vppcalls.go
plugins/vpp/l2plugin/vppcalls/interface_vppcalls_test.go
plugins/vpp/l2plugin/vppcalls/l2fib_vppcalls.go
plugins/vpp/watch_events.go

fixed occasional fib configuration failures

---

plugins/linux/ifplugin/data_resync.go

do not interrupt linux resync on error

---

plugins/govppmux/options.go
plugins/vpp/l2plugin/bd_config.go
plugins/vpp/l2plugin/bd_config_test.go
plugins/vpp/l2plugin/fib_config.go
plugins/vpp/l2plugin/l2idx/bd_index.go
plugins/vpp/l2plugin/l2idx/bd_index_test.go
plugins/vpp/l2plugin/vppcalls/api_vppcalls.go
plugins/vpp/l2plugin/vppcalls/interface_vppcalls.go
plugins/vpp/l2plugin/vppcalls/interface_vppcalls_test.go
plugins/vpp/l2plugin/vppcalls/l2fib_vppcalls.go
plugins/vpp/watch_events.go

(contiv) fix for occassional fib configuration issue

---

plugins/linux/ifplugin/data_resync.go

(contiv) do not fail linux interface resync on error

---

plugins/vpp/ifplugin/nat_config.go
plugins/vpp/ifplugin/vppcalls/nat_vppcalls.go
plugins/vpp/ifplugin/vppcalls/nat_vppcalls_test.go

(contiv) nat tag length check

---

Makefile

Build enhancements

---

plugins/linux/ifplugin/data_resync.go

linux resync registers also veth-type interfaces

---

tests/robot/variables/common_variables.robot

SFC change image 2

---

plugins/vpp/binapi/nat/nat.ba.go
vpp.env

Update VPP to v18.10-rc0+434

---

tests/robot/libraries/docker.robot
tests/robot/variables/common_variables.robot

faster suite setup/cleanup

---

plugins/linux/ifplugin/data_resync.go
plugins/linux/ifplugin/interface_config.go

Fix concurrent map access in LinuxInterfaceConfigurator

---

tests/robot/libraries/SshCommons.robot
tests/robot/libraries/common_setup-teardown.robot
tests/robot/libraries/docker.robot
tests/robot/libraries/linux.robot
tests/robot/libraries/lm_term.robot
tests/robot/libraries/pretty_keywords.robot
tests/robot/libraries/rest_api.robot
tests/robot/libraries/setup-teardown.robot
tests/robot/libraries/ssh.robot

shh library logging

---

tests/robot/libraries/common_setup-teardown.robot
tests/robot/libraries/docker.robot
tests/robot/libraries/kubernetes/KubeSetup.robot
tests/robot/libraries/setup-teardown.robot
tests/robot/libraries/ssh.robot
tests/robot/suites/crud/ipsec_crud.robot

sssh logging2

---

tests/robot/lists/list_api.txt
tests/robot/lists/list_crud_ipv4.txt
tests/robot/lists/list_crud_ipv6.txt
tests/robot/lists/list_intregration_restarts.txt
tests/robot/lists/list_misc.txt
tests/robot/lists/list_sfc_ipv4.txt
tests/robot/lists/list_sfc_ipv6.txt
tests/robot/lists/list_traffic_ipv4.txt
tests/robot/lists/list_traffic_ipv6.txt

added lists of test suites selected for actual testing

---

tests/robot/lists/list_crud_ipv6.txt

deletedEOF from list file

---

docker/dev/build.sh

Fixed the part of download link for protobuf (PROTOC_OS_ARCH)

---

tests/robot/suites/traffic/veth_af_packet_traffic/veth_af_packet_traffic.robot
tests/robot/suites/trafficIPv6/veth_af_packet_traffic/veth_af_packet_trafficIPv6.robot

Change test Tag

---

plugins/vpp/l3plugin/vppcalls/route_dump.go

Drop-type route path dumped from the newest VPP do not longer have TableID field filled, so for VRF != 0 it matched the condition for inter-vrf type. 
Also, the interface index field is correctly set with max value if there is no interface in the route.

fix vpp route type dump

---

tests/robot/libraries/common_setup-teardown.robot
tests/robot/libraries/docker.robot
tests/robot/libraries/kubernetes/KubeSetup.robot
tests/robot/libraries/setup-teardown.robot
tests/robot/libraries/ssh.robot

Change ssh timeout

---

tests/robot/libraries/docker.robot
tests/robot/libraries/setup-teardown.robot
tests/robot/suites/crud/inter_vrf_routing_crud.robot
tests/robot/suites/crud/linux_arp_crud.robot
tests/robot/suites/crud/srv6_crud.robot
tests/robot/variables/common_variables.robot

Kafka ommited in tests

---

tests/robot/suites/crud/linux_arp_crud.robot

fix in linux arp tests

---

CHANGELOG.md

v1.7 changelog

---

tests/robot/suites/crud/linux_arp_crud.robot

fixed linux-arp test2

---

tests/robot/libraries/docker.robot
tests/robot/suites/traffic/veth_af_packet_traffic/veth_af_packet_traffic.robot
tests/robot/variables/common_variables.robot

vpp_agent image used for non vpp nodes

---

plugins/linux/data_resync.go
plugins/linux/linuxplugin_init.go
plugins/linux/watch_events.go
plugins/vpp/data_resync.go
plugins/vpp/plugin_impl_vpp.go

added error propagation and revision logging to vpp/linux event watcher

---

tests/robot/suites/sfc/traffic/veth_af_packet_traffic/sfc_veth_af_packet_traffic.robot
tests/robot/suites/sfc/traffic/veth_af_packet_traffic/test_data/veth_basic.conf

SFC test fix

---

tests/robot/suites/sfcIPv6/test_controller_start/controller_startIPv6.robot
tests/robot/suites/sfcIPv6/test_controller_start/test_data/simpleIPv6.conf

Fix sfc IPv6 test

---

plugins/vpp/ifplugin/vppcalls/dump_interface_vppcalls.go

support for rx-mode/placement dump

---

cmd/agentctl/impl/interfaces.go

change the agentctl's PutLookback API from InterfaceType_TAP_INTERFACE to InterfaceType_SOFTWARE_LOOPBACK

debug the tool of agentctl PutLookback API

---

tests/robot/libraries/vat_term.py
tests/robot/suites/trafficIPv6/ip_route/test1_ip_routeIPv6.robot
tests/robot/suites/trafficIPv6/ip_route/test2_ip_routeIPv6.robot
tests/robot/suites/trafficIPv6/ip_route/test3_ip_routeIPv6.robot
tests/robot/suites/trafficIPv6/ip_route/test4_ip_routeIPv6.robot

fix traffic iproute test

---

tests/robot/suites/trafficIPv6/ip_route/test3_ip_routeIPv6.robot
tests/robot/suites/trafficIPv6/ip_route/test4_ip_routeIPv6.robot

fix trafficIPv6 iproute test

---

tests/robot/suites/trafficIPv6/tap_int_traffic/tap_int_trafficIPv6.robot

fix tap traffic test

---

tests/robot/suites/trafficIPv6/bridge_domain/test1_bridge_domainIPv6.robot

fix BD traffic test IPv6

---

tests/robot/suites/traffic/l2xconnect_traffic/l2xconnect_trafic.robot
tests/robot/suites/trafficIPv6/l2xconnect_traffic/l2xconnect_traficIPv6.robot

fix l2xconnect remove expected fail

---

tests/robot/suites/crudIPv6/app_namespaces_crudIPv6.robot

fix app namespaces test

---

plugins/linux/ifplugin/linuxcalls/dump_link_linuxcalls.go

(master) fix linux interface dump for default namespace

---

plugins/vpp/ifplugin/interface_config.go
plugins/vpp/ifplugin/interface_config_test.go

re-enble VRF configuration for vxlan tunnels

---

plugins/vpp/binapi/ip/ip.ba.go
vpp.env

[master] Update VPP to v19.01-rc0-29-g02a95ce8 (CSIT checkpoint)

---

docker/dev/Dockerfile

added python-cffi installation in Docker file

---

plugins/kvscheduler/txn_record.go

KVScheduler: handle multi-line txn descriptions.

---

tests/robot/suites/crudIPv6/linux_ip_route_crudIPv6.robot

Fix IPv6 linux route test

---

plugins/linuxv2/model/l3/keys.go
plugins/vppv2/ifplugin/ifaceidx/ifaceidx.go
plugins/vppv2/ifplugin/ifaceidx/ifaceidx_test.go

interface idxmap v2: allow to list all interfaces in the mapping

---

plugins/linux/ifplugin/linuxcalls/dump_link_linuxcalls.go

linux if dump uses correct name to read links

---

plugins/linux/nsplugin/ns_handler.go

do not leave file opened on unsuccessful ns switch

---

tests/robot/libraries/etcdctl.robot
tests/robot/libraries/pretty_keywords.robot
tests/robot/resources/static_route.json
tests/robot/suites/crud/ip_route_crud.robot

Scheduler v2 fin ip_route test

---

tests/robot/resources/veth_interface_with_ip.json

fix veth with ip data

---

plugins/vppv2/l2plugin/descriptor/bridgedomain.go
plugins/vppv2/l2plugin/vppcalls/api_vppcalls.go
plugins/vppv2/l2plugin/vppcalls/dump_vppcalls.go
plugins/vppv2/l2plugin/vppcalls/dump_vppcalls_test.go

(dev) bridge domain dump returns a list instead of map

---

tests/robot/libraries/etcdctl.robot
tests/robot/libraries/rest_api.robot

fixed bd crud suite

---

tests/robot/resources/linux_static_route.json
tests/robot/resources/linux_static_route_without_interface.json
tests/robot/resources/linux_veth_interface.json

Fix linux route test

---

tests/robot/suites/crud/linux_arp_crud.robot

Fix linux arp test, remove lo

---

tests/robot/suites/crudIPv6/ip_route_crudIPv6.robot

Fix ip riute crud ipv6 test

---

plugins/linux/ifplugin/interface_state.go

Fix crash in processing of linux notifications

---

plugins/vppv2/natplugin/vppcalls/nat_vppcalls.go

This is https://github.com/ligato/vpp-agent/pull/1042 applied to natplugin v.2
Please make sure that all fixes applied to v1 plugins are also propagated to v2 plugins (if still relevant), thanks!

natplugin v2: Avoid overflow in dnat lb programming

---

plugins/vpp/aclplugin/vppcalls/acl_vppcalls.go

fix potential crash in acl tcp/udp/icmp rules

---

tests/robot/libraries/etcdctl.robot

Fix ipv6 localhost

---

tests/robot/libraries/vpp_term.robot

fix for No match found for vpp

---

docker/prod/supervisord_kill.py
plugins/govppmux/plugin_impl_govppmux.go

(v1.5) removed troubling log & expected error from supervisord script

---

tests/robot/suites/trafficIPv6/ip_route/test4_ip_routeIPv6.robot

Fix traffic IPv6 dev test

---

tests/robot/suites/trafficIPv6/ip_route/test4_ip_routeIPv6.robot

fix test for traffic ipv6

---

plugins/vpp/binapi/ip/ip.ba.go
plugins/vpp/binapi/l2/l2.ba.go
plugins/vpp/binapi/session/session.ba.go
vpp.env

update VPP to v19.01-rc0~394-g6b4a32de (vpp checkpoint)

---

cmd/agentctl/impl/interfaces.go
docker/dev/logs.conf
plugins/vpp/binapi/interfaces/interfaces.ba.go
plugins/vpp/binapi/ip/ip.ba.go
plugins/vpp/binapi/ipsec/ipsec.ba.go
plugins/vpp/binapi/l2/l2.ba.go
plugins/vpp/binapi/session/session.ba.go
plugins/vpp/l2plugin/vppcalls/arp_term_vppcalls.go
plugins/vpp/l2plugin/vppcalls/arp_term_vppcalls_test.go
vpp.env

master -> pantheon-dev

---

plugins/vpp/rpc/services.go

fixed panic if vpp plugin is not defined in rpc plugin

---

cmd/vpp-agent-ctlv2/json/ip-redirect.json
cmd/vpp-agent-ctlv2/json/punt-to-host.json
plugins/vppv2/puntplugin/README.md

punt plugin documentation

---

tests/robot/suites/crud/ipsec_crud.robot
tests/robot/suites/crudIPv6/ipsec_crudIPv6.robot

ipsec test add wait until

---

tests/robot/suites/crud/arp_crud.robot

fix arp_crud test

---

tests/robot/suites/crudIPv6/ipsec_crudIPv6.robot

fix ipsec crud ipv6

---

tests/robot/resources/tap_interface_unnumbered.json
tests/robot/suites/crud/tap_unnumbered_crud.robot
tests/robot/suites/crudIPv6/tap_unnumbered_crudIPv6.robot

fix unnumbered tap test

---

plugins/kvscheduler/api/errors.go
plugins/kvscheduler/api/kv_scheduler_api.go
plugins/kvscheduler/api/txn_record.go
plugins/kvscheduler/datachange_test.go
plugins/kvscheduler/notification_test.go
plugins/kvscheduler/plugin_scheduler.go
plugins/kvscheduler/rest.go
plugins/kvscheduler/resync_test.go
plugins/kvscheduler/txn_exec.go
plugins/kvscheduler/txn_process.go
plugins/kvscheduler/txn_queue.go
plugins/kvscheduler/txn_record.go
plugins/kvscheduler/value_flags.go

kvscheduler: expose transaction history.

---

plugins/vpp/rpc/services.go

fixed occasional pointless recovery in grpc plugin

---

tests/robot/suites/traffic/3x_vpp_traffic/3x_vpp_traffic.robot

Fix 3x vpp traffic test

---

plugins/linuxv2/l3plugin/descriptor/arp.go
plugins/linuxv2/l3plugin/descriptor/route.go

l3 plugin Dump: handle removed namespace

---

cmd/vpp-agent-ctlv2/json/afpacket.json
cmd/vpp-agent-ctlv2/json/loop.json
cmd/vpp-agent-ctlv2/json/memif.json
cmd/vpp-agent-ctlv2/json/tap.json
cmd/vpp-agent-ctlv2/json/vxlan.json

fix interface-related json example files

---

clientv2/linux/data_change_api.go
clientv2/linux/data_resync_api.go
clientv2/linux/dbadapter/data_change_db.go
clientv2/linux/dbadapter/data_resync_db.go
clientv2/vpp/data_change_api.go
clientv2/vpp/data_resync_api.go
clientv2/vpp/dbadapter/data_change_db.go
clientv2/vpp/dbadapter/data_resync_db.go

Update clientv2 to include ipsec and punt plugins.

---

plugins/linuxv2/model/interfaces/keys.go
plugins/vppv2/model/interfaces/keys.go

Fix json marshalling of interfaces dump

---

plugins/linuxv2/model/interfaces/keys.go
plugins/vppv2/model/interfaces/keys.go

Add UnmarshalJSON method for interfaces

---

docker/prod/vpp.conf
tests/robot/resources/vpp_nat.conf

add statseq to vpp conf

---

tests/robot/libraries/etcdctl.robot
tests/robot/libraries/pretty_keywords.robot

fix keys after change in tests

---

plugins/kvscheduler/rest.go
plugins/kvscheduler/txn_exec.go
plugins/kvscheduler/txn_process.go

Several bug fixes for kvscheduler.

---

cmd/vpp-agent/app/v2/vpp_agent.go
pkg/util/proto.go
plugins/vppv2/ifplugin/ifplugin.go
plugins/vppv2/ifplugin/interface_state.go
plugins/vppv2/puntplugin/descriptor/ip_punt_redirect.go
plugins/vppv2/puntplugin/puntplugin.go
plugins/vppv2/puntplugin/vppcalls/api_vppcalls.go
plugins/vppv2/puntplugin/vppcalls/dump_vppcalls.go
plugins/vppv2/puntplugin/vppcalls/punt_vppcalls.go

This PR implements publishing of registered sockets to KVDB.

Publish registered punt socket to KVDB

---

docker/dev/Dockerfile
docker/prod/Dockerfile

Fix renamed VPP deb packages

---

plugins/kvscheduler/graphviz.go
plugins/kvscheduler/rest.go

- mark nodes updated in the selected transaction with a gold, thick border
- link graph node record data (JSON)

kvscheduler: graph improvements

---

Gopkg.lock
pkg/util/proto.go
plugins/kvscheduler/api/errors.go
plugins/kvscheduler/api/txn_record.go
plugins/kvscheduler/internal/utils/conversions.go
plugins/kvscheduler/refresh.go
plugins/orchestrator/dispatcher.go
vendor/github.com/pkg/errors/.travis.yml
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/stack.go

- enhanced debug logs
- fix conversion from proto Empty in ProtoToString
- round timestamps and duration
- use github.com/pkg/errors package for creating errors

KVScheduler improvements

---

plugins/linuxv2/l3plugin/descriptor/arp.go
plugins/linuxv2/l3plugin/descriptor/route.go

Linux routes and ARPs also depend on the target interface to have IP address

---

Makefile
plugins/configurator/configurator.go
plugins/linux/ifplugin/linuxcalls/mock_linuxcalls.go

Fix the missed import

---

docker/prod/Dockerfile

Fix deb package names for production image

---

CHANGELOG.md

Signed-off-by: Vladimir Lavor [vlavor@cisco.com](mailto:vlavor@cisco.com)

agent 2.0 changelog draft

---

plugins/vpp/binapi/vpp1810/ip/ip.ba.go
plugins/vpp/binapi/vpp1810/sr/sr.ba.go

Apply patch to vpp1810 generated binapi

---

plugins/kvscheduler/internal/graph/graph_read.go
plugins/kvscheduler/notification_test.go
plugins/kvscheduler/resync_test.go
plugins/kvscheduler/txn_exec.go
plugins/kvscheduler/txn_record.go

WIP: Re-enabling and fixing kvscheduler UTs.

---

plugins/vpp/ifplugin/descriptor/interface_crud.go

* Af-Packet interface can have the mac address assigned. The address is used from the host only if not provided from the configuration
* Added check for rx-placement. The af-packet interface rx-placement is automatically set in the latest VPP, thus retrieved during resync. The missing check caused the agent to crash in an attempt to 'update' rx-placement with empty value.

af-packet fixes

---

plugins/vpp/ifplugin/descriptor/interface.go

do not retry error where the DPDK interface is missing

---

api/models/linux/interfaces/keys.go
plugins/linux/ifplugin/descriptor/interface.go

Properly handle linuxIf IP without mask

---

plugins/govppmux/vppcalls/vpp1810/vpe_vppcalls.go
plugins/govppmux/vppcalls/vpp1901/vpe_vppcalls.go
plugins/govppmux/vppcalls/vppcalls_api.go

Add ping to vpe-related vppcalls.

---

cmd/vpp-agent-ctl/data/ifplugin.go
plugins/linux/ifplugin/descriptor/interface.go

Linux IF: attempt to add already assing IP is not err

---

plugins/kvscheduler/datachange_test.go
plugins/kvscheduler/notification_test.go
plugins/kvscheduler/txn_exec.go

Fix and re-enable remaining kvscheduler UTs.

---

plugins/linux/ifplugin/descriptor/interface.go

Linux if: Improve err comaprison

---

tests/robot/examples/example_crud_test.robot
tests/robot/suites/crudIPv6/acl_crudIPv6.robot

add test example and fix aclip6

---

plugins/linux/ifplugin/descriptor/interface_loop.go

Fix delete of linux loop

---

docs/README.md
docs/tutorials/README.md

link tutorials to ligato.io

---

tests/robot/libraries/etcdctl.robot
tests/robot/suites/crudIPv6/bd_crudIPv6.robot
tests/robot/suites/traffic/veth_afpacket_memif_vxlan_traffic/veth_afpacket_memif_vxlan_traffic_other_vrf.robot
tests/robot/suites/traffic/vpp_2novpp_memif_traffic/vpp_2novpp_memif_traffic.robot

fix and optimize 1.0

---

README.md
examples/README.md

removed doc references that the kafka is required

---

plugins/telemetry/config.go
plugins/telemetry/prometheus.go
plugins/telemetry/telemetry.go
plugins/telemetry/vppcalls/vpp1810/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vpp1901/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vpp1901/telemetry_vppcalls_test.go
plugins/telemetry/vppcalls/vppcalls_api.go

Fix retrieving VPP metrics in telemetry plugin

---

docs/tutorials/07_vpp-connection.md
docs/tutorials/README.md
examples/tutorials/07_vpp-connection/main.go

tutorial: synchronous/asynchronous configuration

---

plugins/kvscheduler/api/errors.go
plugins/kvscheduler/descriptor_handler.go
plugins/kvscheduler/node_utils.go
plugins/kvscheduler/notification_test.go
plugins/kvscheduler/plugin_scheduler.go
plugins/kvscheduler/refresh.go
plugins/kvscheduler/txn_exec.go
plugins/kvscheduler/txn_order.go
plugins/kvscheduler/txn_process.go
plugins/linux/ifplugin/descriptor/interface.go
plugins/linux/nsplugin/linuxcalls/namespace_api.go

kvscheduler: add check for the preservation of the net namespace + refresh bug fix

---

Gopkg.lock
plugins/govppmux/govpp.conf
plugins/govppmux/plugin_impl_govppmux.go
vendor/git.fd.io/govpp.git/adapter/socketclient/socketclient.go
vendor/git.fd.io/govpp.git/adapter/vppapiclient/stat_client.go
vendor/git.fd.io/govpp.git/adapter/vppapiclient/vppapiclient.go
vendor/git.fd.io/govpp.git/core/channel.go
vendor/git.fd.io/govpp.git/core/connection.go

* attempt to connect to the vpp using socket client checks existence of the socket file
* configurable number of reconnection attempts and delays between them

fix for socketclient connection

---

docker/dev/Dockerfile
docker/prod/Dockerfile

Signed-off-by: Mathieu Rohon <mathieu.rohon@orange.com>

Run supervisord as process with PID 1

---

CHANGELOG.md

release notes v2.0.1

---

.travis.yml

travis move to xenial

---

plugins/vpp/ifplugin/vppcalls/vpp1901/ipsec_vppcalls_test.go

add ipsec unit test 1901

---

plugins/vpp/l3plugin/vppcalls/vpp1810/arp_dump.go
plugins/vpp/l3plugin/vppcalls/vpp1901/arp_dump.go
plugins/vpp/l3plugin/vppcalls/vpp1904/arp_dump.go

fixed arp v6 retrieve

---

clientv2/vpp/data_resync_api.go

added abf option to the resync api in the client v2

---

plugins/govppmux/adapter_stubs.go
plugins/govppmux/adapter_vppapiclient.go
plugins/govppmux/govpp.conf
plugins/govppmux/plugin_impl_govppmux.go

Some would want to have this configurable via the config file...

govppmux: allow to choose between shm & socket using a config option

---

plugins/vpp/ifplugin/descriptor/interface_vrf.go

Explicitly set vrf=0 for numbered interfaces

---

plugins/kvscheduler/stats.go
plugins/kvscheduler/txn_exec.go
plugins/kvscheduler/txn_process.go
plugins/kvscheduler/txn_record.go

Example:
```
"TxnStats": {
"TotalProcessed": 2,
"OperationCount": {
"CREATE": 22,
"DELETE": 2,
"UPDATE": 2
},
"ValueStateCount": {
"CONFIGURED": 19,
"DISCOVERED": 0,
"FAILED": 0,
"INVALID": 2,
"MISSING": 0,
"NONEXISTENT": 0,
"OBTAINED": 0,
"PENDING": 4,
"REMOVED": 1,
"RETRYING": 0,
"UNIMPLEMENTED": 0
},
"ErrorCount": 2,
"Methods": [
{
"Name": "processTransaction",
"Count": 2,
"Total": "546.42ms",
"Avg": "273.21ms",
"Min": "49.05ms",
"Max": "497.37ms"
},
{
"Name": "preProcessTransaction",
"Count": 2,
"Total": "340.82ms",
"Avg": "170.41ms",
"Min": "0s",
"Max": "340.82ms"
},
{
"Name": "executeTransaction",
"Count": 2,
"Total": "199.99ms",
"Avg": "100ms",
"Min": "45.44ms",
"Max": "154.56ms"
},
{
"Name": "recordTransaction",
"Count": 2,
"Total": "3.25ms",
"Avg": "1.62ms",
"Min": "1.12ms", …
```

Kvscheduler transaction statistics

---

plugins/vpp/ifplugin/vppcalls/vpp1904/ipsec_vppcalls_test.go
plugins/vpp/ifplugin/vppcalls/vpp1904/subif_vppcals_test.go

add unit tests to 1904

---

plugins/vpp/ifplugin/vppcalls/vpp1901/watch_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1901/watch_vppcalls_test.go
plugins/vpp/ifplugin/vppcalls/vpp1904/watch_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1904/watch_vppcalls_test.go
plugins/vpp/vppcallmock/vpp_ctx_mock.go

unit test watch_vppcals

---

tests/robot/libraries/pretty_keywords.robot
tests/robot/suites/crud/inter_vrf_routing_crud.robot
tests/robot/suites/crud/ip_route_crud.robot
tests/robot/suites/crudIPv6/inter_vrf_routing_crud_ipv6.robot
tests/robot/suites/crudIPv6/ip_route_crudIPv6.robot
tests/robot/suites/traffic/ip_route/test_inter_vrf_routes.robot
tests/robot/suites/trafficIPv6/ip_route/test_inter_vrf_routes_ipv6.robot

fix non zero vrf

---

plugins/vpp/ifplugin/vppcalls/vpp1901/watch_vppcalls_test.go
plugins/vpp/ifplugin/vppcalls/vpp1904/watch_vppcalls_test.go

Interface plugin 'watch' unit-tests cleanup

---

tests/robot/resources/tap_interface_unnumbered.json
tests/robot/suites/crud/app_namespaces_crud.robot
tests/robot/suites/crud/l2xconnect_crud.robot
tests/robot/suites/crud/stn_rule_crud.robot
tests/robot/suites/crud/tap_unnumbered_crud.robot

change tap to tapv2

---

tests/robot/libraries/etcdctl.robot
tests/robot/libraries/pretty_keywords.robot
tests/robot/suites/crud/arp_crud.robot
tests/robot/suites/crud/linux_ip_route_crud.robot
tests/robot/suites/crudIPv6/arp_crudIPv6.robot
tests/robot/suites/crudIPv6/linux_ip_route_crudIPv6.robot

fix robot tests

---

plugins/linux/ifplugin/descriptor/interface.go

Try enabling ipv6 for linux interface with sysctl

---

examples/tutorials/08_grpc/cmd/client/main.go
examples/tutorials/08_grpc/plugins/grpc/grpc_client.go
examples/tutorials/08_grpc/plugins/grpc/options.go

added grpc tutorial code

---

tests/robot/libraries/vpp_term.robot
tests/robot/resources/vpp_nat.conf
tests/robot/suites/crud/ipsec_crud.robot
tests/robot/suites/crud/l2xconnect_crud.robot
tests/robot/suites/crudIPv6/ipsec_crudIPv6.robot
tests/robot/suites/crudIPv6/l2xconnect_crudIPv6.robot

fix robot tests ipsec nat l2x

---

tests/robot/libraries/etcdctl.robot
tests/robot/suites/traffic/ip_route/test_ip_route.robot
tests/robot/suites/traffic/tap_int_traffic/tap_int_traffic.robot
tests/robot/suites/traffic/veth_afpacket_memif_vxlan_traffic/veth_afpacket_memif_vxlan_traffic.robot
tests/robot/suites/trafficIPv6/tap_int_traffic/tap_int_trafficIPv6.robot
tests/robot/suites/trafficIPv6/veth_afpacket_memif_vxlan_traffic/veth_afpacket_memif_vxlan_trafficIPv6.robot

fix test acl, traffic tests

---

examples/kvscheduler/nat/main.go

Update NAT example for VPP 19.04.

---

CHANGELOG.md
README.md

changelog + readme updated and cleaned up

---

CHANGELOG.md

changelog for vpp-agent v2.1

---

tests/robot/libraries/etcdctl.robot
tests/robot/suites/crudIPv6/linux_arp_crudIPv6.robot
tests/robot/suites/traffic/l2xconnect_traffic/l2xconnect_trafic.robot
tests/robot/suites/trafficIPv6/l2xconnect_traffic/l2xconnect_traficIPv6.robot

fix robot test

---

cmd/vpp-agent/main.go

This PR adds env vars for overriding start/stop timeouts for agent.

Define env vars for overriding start/stop timeouts of agent

---

plugins/telemetry/metrics.go
plugins/telemetry/prometheus.go
plugins/telemetry/telemetry.go
plugins/telemetry/vppcalls/vpp1901/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vpp1904/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vppcalls_api.go

Add interfaces metrics to telemetry plugin

---

plugins/orchestrator/orchestrator.go

Improve error logs for invalid key value pairs

---

Makefile
docker/dev/Dockerfile
docker/dev/build.sh
docker/prod/Dockerfile
docker/prod/build.sh

Allow skipping binapi check in dev docker image

---

Gopkg.lock
plugins/vpp/binapi/vpp1908/ip/ip.ba.go
plugins/vpp/binapi/vpp1908/ipsec/ipsec.ba.go
plugins/vpp/binapi/vpp1908/l2/l2.ba.go
plugins/vpp/binapi/vpp1908/nat/nat.ba.go
plugins/vpp/binapi/vpp1908/punt/punt.ba.go
plugins/vpp/binapi/vpp1908/session/session.ba.go
plugins/vpp/puntplugin/vppcalls/vpp1908/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/punt_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/punt_vppcalls_test.go
vendor/git.fd.io/govpp.git/adapter/socketclient/socketclient.go
vendor/git.fd.io/govpp.git/adapter/stats_api.go
vendor/git.fd.io/govpp.git/adapter/vppapiclient/stat_client.go
vendor/git.fd.io/govpp.git/adapter/vppapiclient/stat_client_wrapper.h
vendor/git.fd.io/govpp.git/cmd/binapi-generator/generate.go
vendor/git.fd.io/govpp.git/cmd/binapi-generator/main.go
vendor/git.fd.io/govpp.git/cmd/binapi-generator/types.go
vpp.env

vpp updated to v19.08-rc0.324-g2ecf18a55

---

plugins/restapi/handlers.go
plugins/restapi/plugin_restapi.go
plugins/restapi/resturl/urls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/dump_vppcalls.go

add rest support for ipsec and punt

---

plugins/configurator/options.go
plugins/configurator/plugin.go

initialize abf plugin handler in configurator

---

cmd/vpp-agent/main.go

Add env var (RESYNC_TIMEOUT) for setting resync timeout

---

plugins/linux/ifplugin/descriptor/interface.go
plugins/linux/nsplugin/ns_plugin.go

- fixed missed error variable
- added logging for several error cases
- improve logging in namespace switching
- add logging for errors from closing namespace handles

Minor enhancements in Linux interface descriptor

---

cmd/vpp-agent-ctl/data/ifplugin.go
cmd/vpp-agent/app/vpp_agent.go
plugins/vpp/ifplugin/ifplugin.go
plugins/vpp/ifplugin/interface_state.go
plugins/vpp/ifplugin/publish_state.go

* e993d3bc6989f671a57915d591d03e21fdc10a44
* 8715c9699d2c713ae532e2aea2c4d51d3a5b6141

reverted acidentally merged commits

---

plugins/configurator/dump.go
plugins/vpp/puntplugin/descriptor/punt_to_host.go
plugins/vpp/puntplugin/vppcalls/punt_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1901/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1904/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/punt_vppcalls.go

punt socket path resolution and L3 'ALL' case

---

plugins/configurator/dump.go
plugins/vpp/puntplugin/descriptor/punt_to_host.go
plugins/vpp/puntplugin/vppcalls/punt_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1901/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1904/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/punt_vppcalls.go

fix punt dump for all vpp versions

---

plugins/configurator/dump.go
plugins/vpp/puntplugin/descriptor/punt_to_host.go
plugins/vpp/puntplugin/vppcalls/punt_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1901/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1904/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/punt_vppcalls.go

Revert "fix punt dump for all vpp versions"

---

pkg/metrics/metrics.go
plugins/govppmux/govpp_channel.go
plugins/govppmux/options.go
plugins/govppmux/plugin_impl_govppmux.go
plugins/govppmux/rest.go
plugins/govppmux/stats.go
plugins/vpp/ifplugin/interface_state.go

cherry picks from vpp1908 branch

govppmux stats REST handler

---

plugins/vpp/puntplugin/descriptor/ip_punt_redirect.go
plugins/vpp/puntplugin/descriptor/punt_exception.go
plugins/vpp/puntplugin/vppcalls/punt_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1901/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1901/punt_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1904/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1904/punt_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/dump_vppcalls.go
plugins/vpp/puntplugin/vppcalls/vpp1908/punt_vppcalls.go

Cleanup puntplugin

---

tests/integration/vpp/001_basic_test.go

added memif interface test to tests/integration

---

tests/integration/vpp/030_arp_test.go

added arp crud integration test

---

plugins/vpp/binapi/vpp1908/bond/bond.ba.go
plugins/vpp/binapi/vpp1908/session/session.ba.go
vpp.env

Update VPP to 19.08-rc0.699-gf7c30df4b

---

vpp.env

Update VPP to 19.08-rc0.706-ga58fec168

---

plugins/vpp/ifplugin/descriptor/interface_crud.go

Signed-off-by: Milan Lenco <milenco@cisco.com>

Fix Retrieve for TAPv2 interface without Linux-side NB config

---

docs/Deployment.md
docs/kvscheduler/kvdescriptor.md
docs/kvscheduler/kvscheduler.md
docs/tutorials/05_kv-scheduler.md

Note: the purpose of this PR is also to test Jenkins change polling

Fixed some typos in documentation

---

client/local_client.go
clientv2/vpp/dbadapter/data_change_db.go
clientv2/vpp/dbadapter/data_resync_db.go
cmd/vpp-agent/app/vpp_agent.go
examples/localclient_with_etcd/README.md
examples/localclient_with_etcd/apply_config_via_etcd.sh
examples/localclient_with_etcd/etcd.conf
examples/localclient_with_etcd/kvscheduler.conf
examples/localclient_with_etcd/list_etcd.sh
examples/localclient_with_etcd/main.go
examples/localclient_with_etcd/run_agent.sh
examples/localclient_with_etcd/run_etcd.sh
plugins/orchestrator/orchestrator.go
plugins/vpp/ifplugin/interface_state.go

Signed-off-by: Milan Lenco <milenco@cisco.com>

Distinguish localclient from other kvdb data sources

---

plugins/vpp/srplugin/descriptor/policy.go

Signed-off-by: Filip Gschwandtner <filip.gschwandtner@pantheon.tech>

Fixing policy delete problem

---

plugins/kvscheduler/internal/utils/record.go

Remove temporary prints used for debugging

---

tests/robot/suites/crud/ipsec_crud.robot
tests/robot/suites/crudIPv6/ipsec_crudIPv6.robot

- update expected data due to API changes

fix ipsec CRUD tests

---

tests/robot/libraries/linux.robot
tests/robot/libraries/vpp_term.robot

- fix "show hardware" command
- rework "Get Interface Presence" keyword to improve error messages

Fix afpacket CRUD tests

---

tests/robot/libraries/etcdctl.robot
tests/robot/libraries/pretty_keywords.robot

update uri for route configuration with no next hop address

fix ip route and inter-vrf route CRUD tests

---

tests/robot/libraries/acl/acl_etcd.robot
tests/robot/libraries/acl/acl_utils.py
tests/robot/libraries/acl/acl_vpp.robot
tests/robot/libraries/all_libs.robot
tests/robot/libraries/configurations.robot
tests/robot/libraries/docker.robot
tests/robot/libraries/setup-teardown.robot
tests/robot/libraries/ssh.robot
tests/robot/libraries/vpp_api.py
tests/robot/libraries/vpp_api.robot
tests/robot/suites/crud/acl_crud.robot
tests/robot/suites/crudIPv6/acl_crudIPv6.robot
tests/robot/tools/vpp_api_executor.py
tests/robot/variables/common_variables.robot

rework ACL CRUD tests to use VPP Python API

---

plugins/vpp/binapi/vpp1908/abf/abf.ba.go
plugins/vpp/binapi/vpp1908/dhcp/dhcp.ba.go
plugins/vpp/binapi/vpp1908/gre/gre.ba.go
plugins/vpp/binapi/vpp1908/interfaces/interfaces.ba.go
plugins/vpp/binapi/vpp1908/ip/ip.ba.go
plugins/vpp/binapi/vpp1908/ipsec/ipsec.ba.go
plugins/vpp/binapi/vpp1908/l2/l2.ba.go
plugins/vpp/binapi/vpp1908/nat/nat.ba.go
plugins/vpp/binapi/vpp1908/punt/punt.ba.go
plugins/vpp/binapi/vpp1908/session/session.ba.go
plugins/vpp/binapi/vpp1908/vpe/vpe.ba.go
plugins/vpp/ifplugin/vppcalls/vpp1908/admin_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1908/admin_vppcalls_test.go
plugins/vpp/ifplugin/vppcalls/vpp1908/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1908/dump_interface_vppcalls_test.go
plugins/vpp/natplugin/vppcalls/vpp1908/dump_nat_vppcalls.go
plugins/vpp/srplugin/vppcalls/vpp1908/srv6.go
plugins/vpp/srplugin/vppcalls/vpp1908/srv6_test.go

Update VPP 19.08 support to v19.08.1-36~g54ff3fc83

---

.travis.yml
plugins/vpp/ifplugin/vppcalls/vpp2001/dump_interface_status_test.go
plugins/vpp/ifplugin/vppcalls/vpp2001/dump_interface_vppcalls.go
tests/integration/vpp/010_interfaces_test.go

fix(vppcalls): Mapping flag for interface states

---

tests/robot/libraries/vpp_api.py

Test: improve logging when VPP API calls fail

---

plugins/telemetry/vppcalls/vpp1904/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vpp1908/telemetry_vppcalls.go
plugins/telemetry/vppcalls/vpp2001/telemetry_vppcalls.go
plugins/vpp/ifplugin/vppcalls/if_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1904/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp1908/dump_interface_vppcalls.go
plugins/vpp/ifplugin/vppcalls/vpp2001/dump_interface_vppcalls.go

This should fix some small bugs i encountered while using vppcalls.
Also added MTU to interface details meta, which is used by vpptop.

fix: possible division by zero and missing mtu

---

CHANGELOG.md

docs: (cherry-pick) changelog for v2.2

---

README.md

This one will resolve issue #1449 completely.
I did cherry-pick commit from PR #1501 
I'm not sure what is title convention for PR with cherry-picked commits.

docs: (cherry-pick) fix link to docs about building local image

---

tests/robot/suites/crud/loopback_crud.robot
tests/robot/suites/crudIPv6/loopback_crudIPv6.robot

test: Remove VAT console from loopback interface CRUD tests

---

tests/robot/suites/crud/stn_rule_crud.robot
tests/robot/suites/crudIPv6/stn_rule_crudIPv6.robot

test: remove VAT console from stn_rule CRUD tests

---

tests/robot/suites/crud/veth_crud.robot
tests/robot/suites/crudIPv6/veth_crudIPv6.robot

test: Remove VAT console from veth interface CRUD tests

---

tests/robot/libraries/interface/vxlan.robot
tests/robot/suites/crud/vxlan_crud.robot
tests/robot/suites/crudIPv6/vxlan_crudIPv6.robot

test: Remove VAT console from vxlan interface CRUD tests

---

tests/robot/suites/crud/tap_unnumbered_crud.robot
tests/robot/suites/crud/tapv2_crud.robot
tests/robot/suites/crudIPv6/tap_unnumbered_crudIPv6.robot
tests/robot/suites/crudIPv6/tapv2_crudIPv6.robot

test: Remove VAT console from tap interface CRUD tests

---

cmd/agentctl/cli/flags.go
cmd/agentctl/commands/root.go

fix: Flags for agentctl

---

CHANGELOG.md

VPP-Agent v2.3.1 changelog

---

plugins/kvscheduler/notification_test.go

This PR is a fix for issue https://github.com/ligato/vpp-agent/issues/1536
Signed-off-by: Milan Lenco <milenco@cisco.com>

test: Fix intermittent failure in kvscheduler unit test

---

Gopkg.lock
vendor/git.fd.io/govpp.git/core/stats.go

fix: Update GoVPP for stats conversion panic (fixes #1540)

---

cmd/agentctl/cli/cli.go
cmd/agentctl/client/api.go
cmd/agentctl/client/kvdb.go
cmd/agentctl/commands/import.go

fix: agentctl import with short keys

---

CHANGELOG.md

I'm not sure if it is correct way of fixing it, so close it without merging if it isn't :)

chore: Fix latest release version in CHANGELOG.md

---

CHANGELOG.md
plugins/configurator/dump.go
plugins/configurator/options.go
plugins/configurator/plugin.go
plugins/linux/ifplugin/descriptor/interface.go
plugins/linux/ifplugin/descriptor/interface_address.go
plugins/linux/ifplugin/descriptor/interface_tap.go
plugins/linux/ifplugin/descriptor/interface_veth.go
plugins/linux/ifplugin/ifplugin.go
plugins/linux/ifplugin/linuxcalls/dump_interface_linuxcalls.go
plugins/linux/ifplugin/linuxcalls/netlink_api.go
plugins/linux/l3plugin/descriptor/arp.go
plugins/linux/l3plugin/descriptor/route.go
plugins/linux/l3plugin/l3plugin.go
plugins/linux/l3plugin/linuxcalls/arp_linuxcalls.go
plugins/linux/l3plugin/linuxcalls/dump_arp_linuxcalls.go
plugins/linux/l3plugin/linuxcalls/dump_route_linuxcalls.go
plugins/linux/l3plugin/linuxcalls/netlink_api.go
plugins/linux/l3plugin/linuxcalls/route_linuxcalls.go
plugins/linux/nsplugin/ns_plugin.go
plugins/restapi/handlers.go
plugins/restapi/options.go
plugins/restapi/plugin_restapi.go
plugins/restapi/resturl/urls.go
plugins/vpp/ifplugin/descriptor/interface_crud.go
plugins/vpp/ifplugin/ifplugin.go
plugins/vpp/ifplugin/options.go
tests/e2e/010_interfaces_test.go
tests/e2e/011_interface_link_only_test.go
tests/integration/vpp/integration_test.go

This is a special release with two new features:
* SRv6 global config (encap source address)
* Support for Linux configuration dumping

Release 2.5.0

---

plugins/vpp/l3plugin/descriptor/vrf_table.go

fix: VRF table origin for SR policy (fixes #1566)

---

plugins/vpp/l3plugin/descriptor/vrf_table.go

fix: VRF table origin for SR policy (dev)

---

CHANGELOG.md

chore: Release 2.5.1

---

cmd/agentctl/commands/model.go

feat: Agentctl output format

---

cmd/agentctl/commands/vpp.go

fix: Agentctl enhancements

---

plugins/linux/ifplugin/descriptor/interface_address.go
tests/e2e/020_netalloc_test.go

fixes TestVPPRoutesWithNetalloc E2E test

fix: check for duplicate Linux interface IP addr

---

plugins/telemetry/options.go
plugins/telemetry/stats_poller.go
plugins/telemetry/telemetry.go

fix: interface name in stats poller service (fixes #1590)

---

buf.yaml
scripts/make/buf.make

ci: Switch to master branch for checking breaking changes

---

go.mod
go.sum

build: Update govpp

---

plugins/vpp/binapi/vpp1908/acl/acl.ba.go
plugins/vpp/binapi/vpp1908/dhcp/dhcp.ba.go
plugins/vpp/binapi/vpp1908/ip/ip.ba.go
plugins/vpp/binapi/vpp1908/ipsec/ipsec.ba.go
plugins/vpp/binapi/vpp1908/l2/l2.ba.go
plugins/vpp/binapi/vpp1908/nat/nat.ba.go

fix: Regenerate binapi VPP 19.08

---

tests/e2e/040_bridge_domain_test.go
tests/e2e/060_acl_test.go
tests/e2e/070_ipsec_test.go
tests/e2e/e2e_test.go
tests/integration/vpp/120_ipip_test.go

test(e2e): Skip IPIP e2e test for VPP <= 19.04

---

plugins/vpp/l3plugin/descriptor/teib_entry.go
plugins/vpp/l3plugin/l3plugin.go

fix: Do not report non-supported teib

---

plugins/linux/iptablesplugin/linuxcalls/iptables_linuxcalls.go

To help resolve missing-iptable-in-host-system case quickly.

refactor: added suggestion in error message for cases of missing iptables in host system

---

tests/e2e/050_nat_test.go

additional testing to PR https://github.com/ligato/vpp-agent/pull/1725

test: added tests for NAT44 pool key changes

---

vpp.env

Solving issue https://github.com/ligato/vpp-agent/issues/1716

build(fix): Updated VPP 20.09 version to obtain VPP fix for e2e nat mappings test

---

cmd/agentctl/commands/config.go
cmd/agentctl/commands/config_test.go

test: Fix unit tests for configurator Notify

---

plugins/configurator/configurator.go
plugins/orchestrator/meta_service.go

feat: allow to differentiate between multiple grpc-based data sources

---

plugins/vpp/l2plugin/vppcalls/vpp2101/dump_vppcalls.go
tests/e2e/020_netalloc_test.go

fix: bugs VPP-1968 and VPP-1970 were fixed in VPP 21.01

---

docker/dev/Dockerfile
docker/prod/Dockerfile

build: Fix VPP config for VPP 20.09

---

plugins/linux/l3plugin/descriptor/route.go

fix: route and netalloc plugin integration

---

CHANGELOG.md
vpp.env

chore: Prepare release notes for v3.3.0

---

proto/ligato/vpp/acl/models.go
proto/ligato/vpp/acl/models_test.go

Signed-off-by: Samuel Dudík <samuel.dudik@pantheon.tech>

Fix ParseACLToInterfaceKey

---

plugins/orchestrator/meta_service.go

fix: Remove unnecessary debug print

---

client/local_client.go
client/remoteclient/grpc_client.go

fix: Correct handling of varargs in GetConfig

---

plugins/orchestrator/orchestrator.go

fix: Create labels map properly

---

vpp.env

Update default VPP version to 22.10

---

CHANGELOG.md
pkg/version/version.go

Signed-off-by: Peter Motičák [peter.moticak@pantheon.tech](mailto:peter.moticak@pantheon.tech)

Update CHANGELOG.md for v3.5.0

---

pkg/version/version.go

Bump version to v3.5.0

---

plugins/kvscheduler/internal/registry/registry_impl.go

fix: Synchronize access to kvscheduler descriptor registry
